### ISSUE TITLE
AttributeError: 'str' object has no attribute 'view'

### ISSUE THREAD

**Issue by Fmq-uo** [THU-MIG/yolov10#10]
![image](https://github.com/THU-MIG/yolov10/assets/74455926/79b61c71-a2b3-44bb-ae76-b6f0a8d30ed9)
Hello, my train.py looks like this, why does running it give me the following error
![image](https://github.com/THU-MIG/yolov10/assets/74455926/e76c8d00-8593-4160-99b9-c8d17ef523c7)

The error code in yolov10 / ultralytics/utils/loss. Py

**Comment by jameslahm** [comment]
Thanks for your interest! Could you please try `YOLOv10(args.config)`?

**Comment by Fmq-uo** [comment]
Thanks for your help, it has been solved




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Wang ***@***.***&gt;; 
发送时间: 2024年5月24日(星期五) 晚上7:40
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [THU-MIG/yolov10] AttributeError: &#39;str&#39; object has no attribute &#39;view&#39; (Issue #10)














 
Thanks for your interest! Could you please try YOLOv10(args.config)?

**Comment by wjq777777** [comment]
I also have the same problem, can you tell me how to correct it？

**Comment by jameslahm** [comment]
Thanks for your interest! Could you please try to use `YOLOv10` rather than `YOLO` to create the model?
> I also have the same problem, can you tell me how to correct it？

**Comment by wjq777777** [comment]
> Do you use the `YOLO` class to create the model?

![image](https://github.com/THU-MIG/yolov10/assets/130145790/a94f6a6a-f4cb-4cf0-9101-e6f2dd40afb0)
Yes, we used the model in the same way as yolov8

**Comment by jameslahm** [comment]
Could you please try to replace `YOLO('weights/yolov10n.pt')` with `YOLOv10('weights/yolov10n.pt')`?
> > Do you use the `YOLO` class to create the model?
> 
> ![image](https://private-user-images.githubusercontent.com/130145790/333588354-a94f6a6a-f4cb-4cf0-9101-e6f2dd40afb0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1NTQ3MDYsIm5iZiI6MTcxNjU1NDQwNiwicGF0aCI6Ii8xMzAxNDU3OTAvMzMzNTg4MzU0LWE5NGY2YTZhLWY0Y2ItNGNmMC05MTAxLWU2ZjJkZDQwYWZiMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNFQxMjQwMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNjA5MjYyM2RlNzM0M2RmMjBkOTY4OTNmNGRhYjExZmM0YzA0NThkMTM0ZjIzNTQyMThiMDg1NTJiNjYxZGE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.euypmOIZ7-XqSEpGgc-yhN8rsMNhEq-ea8rNWtd6v3U) Yes, we used the model in the same way as yolov8

**Comment by weldingCode** [comment]
> Thanks for your interest! Could you please try `YOLOv10(args.config)`?

NameError: name 'YOLOv10' is not defined

**Comment by jameslahm** [comment]
`YOLOv10` can be imported from `ultralytics`, like below
```
from ultralytics import YOLOv10
```

**Comment by liangsiping2019** [comment]
> `YOLOv10` can be imported from `ultralytics`, like below
> 
> ```
> from ultralytics import YOLOv10
> ```

Thanks, the problem has been solved！

**Comment by buaazhl** [comment]
Thank you for your response, the issue has been resolved！

**Comment by yrangana** [comment]
Get the same error when executed in CLI, but only resume training. Any idea to fix in CLI

`pred_distri, pred_scores = torch.cat([xi.view(feats[0].shape[0], self.no, -1) for xi in feats], 2).split(
AttributeError: 'str' object has no attribute 'view'`

**Comment by jameslahm** [comment]
@yrangana Thanks for your interest! Does this issue #46 help?

**Comment by EngHanaa** [comment]
I need to continue from last.pt file, but u have the same error "AttributeError: 'str' object has no attribute 'view'", also i have used YOLOv10 instead of YOLOv. How can i solve that?

**Comment by jameslahm** [comment]
@EngHanaa Thanks for your interest! Could you please the details of how to reproduce this issue?
> I need to continue from last.pt file, but u have the same error "AttributeError: 'str' object has no attribute 'view'", also i have used YOLOv10 instead of YOLOv. How can i solve that?

**Comment by sanha9999** [comment]
@EngHanaa change the name of the .pt file to include "yolov10" and try.

**Comment by wangqiqi** [comment]
how to solve this when use the CLI, 
I trained the model use the cmd:  `yolo task=..........` as this, how to fix the problem??

**Comment by pillai-karthik** [comment]
> @EngHanaa change the name of the .pt file to include "yolov10" and try.

Weird but this worked for me! Thank you

**Comment by wrecka98** [comment]
Hi! Running into the same issue, but I am using YOLOv11. Trying to import YOLOv11 or YOLOv10 from ultralytics results in an error. How can I solve this?
