### ISSUE TITLE
Why can't I reproduce your results, and at the same time, there is a significant difference in FLOPS?

### ISSUE THREAD

**Issue by oahcang** [THU-MIG/yolov10#102]

**Comment by jameslahm** [comment]
Thanks for your interest! Could you please provide more details?

**Comment by jameslahm** [comment]
Does this issue #13 help?

**Comment by obisidianouc** [comment]
> > Thanks for your interest! Could you please provide more details?
> 
> Under the same conditions, I tested your v10n model to be 8.6 while in Performance it is 6.7, V10s is 24.8

I find the same issue. The inference time of v10n is about 8, and of v8n is about 6 on A100 (huggingface ZeroGPU)

**Comment by jameslahm** [comment]
Thanks for your interest! Could you please provide the details of the benchmark and the results?

> I find the same issue. The inference time of v10n is about 8, and of v8n is about 6 on A100 (huggingface ZeroGPU)

**Comment by jameslahm** [comment]
Please feel free to reopen this issue if you have further questions.
