### ISSUE TITLE
What's the relationship between yolov10s.yaml and yolov10s.pt

### ISSUE THREAD

**Issue by hopeSerendipity** [THU-MIG/yolov10#106]
When I try to train a model with yolov10s.yaml, it downloads yolov8n.pt instead of yolov10s.pt. Does this mean that yolov10s.pt is only used for prediction and not for training?

**Comment by puffy310** [comment]
I'm guessing this is an error from legacy codebase. This is what happens when different teams just keep going up in version numbers. yolo v8 might be only the first or second iteration so it skips a generation because some other team already did 9.

**Comment by jameslahm** [comment]
Thanks for your interest! No worries, the `yolov8n.pt` is only downloaded once and is used to check if the `amp` works in your environment.
> When I try to train a model with yolov10s.yaml, it downloads yolov8n.pt instead of yolov10s.pt. Does this mean that yolov10s.pt is only used for prediction and not for training?

**Comment by hopeSerendipity** [comment]
But when I train the model, it didn't download yolov10s.pt; only yolov8n.pt was downloaded.Is this a normal state?

**Comment by jameslahm** [comment]
Yes, it is normal. The `yolov8n.pt` is downloaded for checking `amp`. And you could download `yolov10s.pt` from [here](https://github.com/THU-MIG/yolov10/releases/tag/v1.1) if you want to use the pretrained model.

**Comment by puffy310** [comment]
I know this is unrelated but is my comment accurate? I'm legitimately wondering.

**Comment by hopeSerendipity** [comment]
> Yes, it is normal. The `yolov8n.pt` is downloaded for checking `amp`. And you could download `yolov10s.pt` from [here](https://github.com/THU-MIG/yolov10/releases/tag/v1.1) if you want to use the pretrained model.

I'm sorry if I bother you.But I want to know if I'm training with yolov10s as a pretained model even I don't download yolov10s.pt.If I'm not training with yolov10s as a pretained model,what's my state now?I'm training without a pretained model?If this is the case  I also want to know how can I train a model with yolov10 as a pretained model.I'm not familiar with this ,so I may ask something seems stupid.

**Comment by jameslahm** [comment]
Thanks. Does this comment https://github.com/THU-MIG/yolov10/issues/114#issuecomment-2137738193 help?

**Comment by hopeSerendipity** [comment]
OK，thank you for your help.
