### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mazilishang** [THU-MIG/yolov10#108]
File "d:\yolo\yolov10-main\ultralytics\utils\loss.py", line 200, in <listcomp>
    pred_distri, pred_scores = torch.cat([xi.view(feats[0].shape[0], self.no, -1) for xi in feats], 2).split(
AttributeError: 'str' object has no attribute 'view'这个错误怎么解决

**Comment by jameslahm** [comment]
Thanks for your interest! Does the issue https://github.com/THU-MIG/yolov10/issues/10 help?

**Comment by jameslahm** [comment]
Please feel free to reopen this issue if you have further questions.
