### ISSUE TITLE
Clarification on APval metric

### ISSUE THREAD

**Issue by V1ad20** [THU-MIG/yolov10#119]
What exactly does the APval metric mean in the following picture?

![image](https://github.com/THU-MIG/yolov10/assets/86973499/e8aaf0d7-7f60-4c57-8343-16038679f98a)

Is it mAP@0.5, mAP@0.75, or mAP@0.5:0.95 at validation? or neither?

**Comment by jameslahm** [comment]
Thanks for your interest! The AP<sup>val</sup> means mAP@0.5:0.95.

**Comment by jameslahm** [comment]
Please feel free to reopen this issue if you have further questions.
