### ISSUE TITLE
Performance alignment about YOLOV10-S

### ISSUE THREAD

**Issue by cdy-for-grad** [THU-MIG/yolov10#124]
hi，it‘s a great project about the YOLO-series. And i tried the training setting with COCO dataset, the result is behind. The performance is  0.45365[mAP50-95]. However, the published performance in this project is 46.3. How can i get the performance  in your project. 

the scripts we use 
`
yolo detect train data=coco.yaml model=yolov10s.yaml epochs=500 batch=256 imgsz=640 device=0,1,2,3,4,5,6,7 --cache 
`

the result 
![image](https://github.com/THU-MIG/yolov10/assets/140789053/b75537f2-d914-4331-a82d-e2947a8c5da8)

Thanks !

**Comment by jameslahm** [comment]
Thanks for your interest! We previously released our training logs [here](https://github.com/THU-MIG/yolov10/tree/main/logs). Could you please take a look at the differences between your training logs and ours? Thank you!

**Comment by cdy-for-grad** [comment]
Thank you for your reply !
without --cache, it will spend too much time in loading COCO dataset, nearly 3-4 hours. 
could you give some advice or any other solutions about it?

**Comment by jameslahm** [comment]
Thanks. We identify an issue about the cache in #84. Does it help?

**Comment by cdy-for-grad** [comment]
could you describe the difference in detail at your free time ?
it is necessary for me to compare the ultralytics file in this project and YOLOv8?

**Comment by jameslahm** [comment]
The difference is attached in the `diff.path` file in https://github.com/THU-MIG/yolov10/issues/84#issuecomment-2136636042. Does it help?

**Comment by SwHaraday** [comment]
Hi,
I've never seen training log which mAP remains the same for several epochs.
Do you know the reason ?

**Comment by jameslahm** [comment]
Thanks for your interest! During training, we set `val_period=10` in `default.yaml` to only perform validation every 10 epochs and the mAP thus remains the same for every 10 epochs.
> Hi, I've never seen training log which mAP remains the same for several epochs. Do you know the reason ?
