### ISSUE TITLE
Problem for train from pretain model

### ISSUE THREAD

**Issue by Sompote** [THU-MIG/yolov10#126]
I try to train the model form pretain model xx.pt. The the error occure.
<img width="1213" alt="Screenshot 2567-05-30 at 09 00 39" src="https://github.com/THU-MIG/yolov10/assets/62241733/f447436c-5e69-41d7-a083-7a05ca89dc22">
<img width="1187" alt="Screenshot 2567-05-30 at 09 00 47" src="https://github.com/THU-MIG/yolov10/assets/62241733/a428e1c4-9e6b-4c71-8b8c-cbd09e51346b">

**Comment by jameslahm** [comment]
Thanks for your interest! Is the `yolov10x.pt` correctly downloaded?

**Comment by Sompote** [comment]
Thank you I can solve it !
