### ISSUE TITLE
When I running the sample code in the yolov10 folder, it skiped into another folder

### ISSUE THREAD

**Issue by 15927566740** [THU-MIG/yolov10#128]
![image](https://github.com/THU-MIG/yolov10/assets/48681680/bb7b6573-831a-4105-adb1-53907ba94673)
As we can see in the picture , when I running the sample code [yolo val model=yolov10s.pt data=coco.yaml batch=256] in the yolov10 folder , it  skiped into another foleder , where can I find the path to set coco.yaml instead of writing it into the command ? to make sure the code running into the correct path ...

**Comment by jameslahm** [comment]
Thanks for your interest! Could you please try to remove `~/.config/Ultralytics/settings.yaml`?

**Comment by 15927566740** [comment]
> Thanks for your interest! Could you please try to remove `~/.config/Ultralytics/settings.yaml`?

yes resolved , I can change the path in coco.yaml after removing settings.yaml ,also can modify setting.yaml strictly.
