### ISSUE TITLE
Exporting tensorRT models is not supported

### ISSUE THREAD

**Issue by Haroldhy** [THU-MIG/yolov10#129]
I use “yolo export model=yolov10n/s/m/b/l/x.pt format=onnx opset=13 simplify”   to export onnx model. 
The exported model contains the fmod(Mod) operator, which is an operator supported by onnx but not by tensorRT, so when exporting the onnx model to a tensorRT model it will report an error. My target version of TensorRT is 8.4.1.

**Comment by jameslahm** [comment]
Thanks for your interest! Does this issue #75 help?

**Comment by Haroldhy** [comment]
Thanks for your answer. The issue indicates that if I don't use the new version of tensorRT, I will need to remove the mod operator from the onnx model, then I will get a model with three outputs. 1x300x4, 1x300x1 and the output of the 1x300 shape that needs to be processed. Then just need to do a mod on the last output right?

**Comment by jameslahm** [comment]
Yes, we think so.

**Comment by jameslahm** [comment]
Please feel free to reopen this issue if you have further questions.

**Comment by jasonlytehouse** [comment]
If you're curious about the code to do this, I have a script called [v10_fixer.py](https://github.com/jayfalls/jetson_nano_ubuntu20_docker/blob/main/yolo/v10_fixer.py) here that does this
