### ISSUE TITLE
How do I export a yolov10 model as an NCNN model?

### ISSUE THREAD

**Issue by zgsxwsdxg** [THU-MIG/yolov10#130]
First of all, thank you for your excellent work.  I'm doing mobile model app development，I would like to ask how to convert the Yolov10 model to the NCNN infer. Can you provide some detailed steps？thanks！

**Comment by jameslahm** [comment]
Thanks for your interest! Does this issue #118 help?

**Comment by jameslahm** [comment]
Please feel free to reopen this issue if you have further questions.
