### ISSUE TITLE
(Feature Request) Detecting Objects in a Video in Realtime

### ISSUE THREAD

**Issue by OtenMoten** [THU-MIG/yolov10#132]
It would be great if I can stream a video to YOLO that detects the objects in a live video.

**Comment by jameslahm** [comment]
Thanks for your interest! You could detect a live video like this
```
wget https://storage.openvinotoolkit.org/repositories/openvino_notebooks/data/data/video/people.mp4
yolo predict model=yolov10s.pt source=people.mp4 conf=0.1
```

**Comment by OtenMoten** [comment]
> Thanks for your interest! You could detect a live video like this
> 
> ```
> wget https://storage.openvinotoolkit.org/repositories/openvino_notebooks/data/data/video/people.mp4
> yolo predict model=yolov10s.pt source=people.mp4 conf=0.1
> ```

I'm still unsure where do I enter commands like `yolo predict model=yolov10s.pt source=people.mp4 conf=0.1` for two reasons:

1.) I use the app via GUI on `http://127.0.0.1:7860`
2.) How do I start the app without GUI as microservice?

And, in the GUI on `http://127.0.0.1:7860` the files filter only allow to select images.

**Comment by OtenMoten** [comment]
UPDATE:

I've figured out that I need to start the python application and access the `venv` in which I can use the command `yolo`. This fact is missing in your `README`.

I've predicted the video, it saves all images to the folder. 

It would be great to see how the video is analyzed live without accessing each single image.

**Comment by leonnil** [comment]
Hi, @OtenMoten

We believe the codebase already supports this feature. Please try using the following command to use the webcam (`source=0`) and display the live-rendered predictions (`show=True`):

```bash
yolo predict model=yolov10n.pt source=0 conf=0.1 show=True
```

Let us know if you have any further questions.

**Comment by OtenMoten** [comment]
Wor

> Hi, @OtenMoten
> 
> We believe the codebase already supports this feature. Please try using the following command to use the webcam (`source=0`) and display the live-rendered predictions (`show=True`):
> 
> ```shell
> yolo predict model=yolov10s.pt source=0 conf=0.1 show=True
> ```
> 
> Let us know if you have any further questions.

Works with `yolo predict model=yolov10s.pt source=0 conf=0.1 show=True`
