### ISSUE TITLE
YoloV10 Onnx/TensorRT NMS to deploy Deepstream/Triton

### ISSUE THREAD

**Issue by ChuRuaNh0** [THU-MIG/yolov10#133]
I create a BatchNMS toolkit for Yolo series to convert onnx, tensorRT with post-processed and attach how to deploy yolo to Deepstream/Triton, you can refer: https://github.com/ChuRuaNh0/Awesome-Yolo-Versions-to-Tensorrt-NMSBatched/tree/main/YOLOv10

**Comment by jameslahm** [comment]
Thank you for your great efforts! Due to that YOLOv10 does not rely on the NMS, it can be directly exported to end2end onnx/TensorRT without the NMS plugin, like https://github.com/THU-MIG/yolov10?tab=readme-ov-file#export

**Comment by levmarki** [comment]
> Thank you for your great efforts! Due to that YOLOv10 does not rely on the NMS, it can be directly exported to end2end onnx/TensorRT without the NMS plugin, like https://github.com/THU-MIG/yolov10?tab=readme-ov-file#export

I'm sorry for stupid question, but if I have a Deepstream with YOLOv8 inside (base on [https://github.com/marcoslucianops/DeepStream-Yolo](url)) what should I do to in order to run YOLOv10 instead of YOLOv8?
Thank you in advance!

**Comment by shashikant-ghangare** [comment]
Hi @levmarki, you can refer to this https://github.com/shashikant-ghangare/DeepStream-Yolo/tree/add-yolov10. I have added support for yolov10 and it works fine

**Comment by levmarki** [comment]
> Hi @levmarki, you can refer to this https://github.com/shashikant-ghangare/DeepStream-Yolo/tree/add-yolov10. I have added support for yolov10 and it works fine

Thank you very much!!

**Comment by jameslahm** [comment]
Thanks for your interest! Please feel free to reopen this issue if you have further questions.

**Comment by matheuz31** [comment]
> Hi @levmarki, you can refer to this https://github.com/shashikant-ghangare/DeepStream-Yolo/tree/add-yolov10. I have added support for yolov10 and it works fine

Hi @shashikant-ghangare ,

First of all, I would like to thank you for the contribution. I've tested your support for YOLOv10 in DeepStream and I'm facing some performance issues. According to the paper, YOLOv10 should be significantly faster than YOLOv8. However, when I run the same pipeline with your YOLOv10 and the @marcoslucianops pipeline with YOLOv8, I find that YOLOv8 has lower latency. Have you faced this problem, or am I missing something?
