### ISSUE TITLE
How do I change the path of the run folder

### ISSUE THREAD

**Issue by mo-lx** [THU-MIG/yolov10#134]
![image](https://github.com/THU-MIG/yolov10/assets/134636320/0622df36-4f26-4d31-b4f1-b3352dabecbb)
The run folder is not stored in the yolov10 folder

**Comment by jameslahm** [comment]
Thanks for your interest! Does this issue #128 help?

**Comment by jameslahm** [comment]
Please feel free to reopen this issue if you have further questions.
