### ISSUE TITLE
Batch infer with multi-GPU

### ISSUE THREAD

**Issue by cdy-for-grad** [THU-MIG/yolov10#138]
Great project !!!
How can i infer a dataset in batch and multi-GPU?

**Comment by jameslahm** [comment]
Thanks for your interest! You could specify `batch` when inferring a dataset in batch, like
```
yolo predict model=yolov10s.pt batch=2
```
For multi-GPU inference, does this issue https://github.com/ultralytics/ultralytics/issues/3953 help?

**Comment by cdy-for-grad** [comment]
Thank you for your reply，another question is about how to resume yolov10 rather than finetuning?

**Comment by jameslahm** [comment]
Does that mean continuing training on COCO?
> Thank you for your reply，another question is about how to resume yolov10 rather than finetuning?

**Comment by cdy-for-grad** [comment]
I mean while start training for some epochs, however some unknown situation would stop the training process.
How can i resume the model from the latest epoch[epoch_10.pth] ?

**Comment by jameslahm** [comment]
Thanks. You could specify the `model` and `resume` argument, like below
```
from ultralytics import YOLOv10

model = YOLOv10('epoch_10.pt')
model.train(resume=True)
```

**Comment by jameslahm** [comment]
Please feel free to reopen this issue if you have further questions.
