### ISSUE TITLE
Open Discussion Tab

### ISSUE THREAD

**Issue by Viddesh1** [THU-MIG/yolov10#145]
Hello,

Thank you for YOLOv10. 

🤔 Opening discussion tab I think will help the commnity to engage more freely with the questions and reasoning.
It will also help is maintaining issues seperate from discussions so general questions can be answer more freely like below issues.

#143 What is meant by iou arguments and what is it's affect?
#142 yolov10-cls?

Also, Appropriate issue can also be created directly from on-going discussions.

Thanks!
Viddesh

**Comment by jameslahm** [comment]
Thanks for your valuable suggestion! We have opened the discussion tab. ❤️

**Comment by Viddesh1** [comment]
Thanks! Closing this issue. :smile:
