### ISSUE TITLE
Questions regarding the training and validation of YOLOv10

### ISSUE THREAD

**Issue by wangqiqi** [THU-MIG/yolov10#148]
1. 同样的数据集（训练，验证，测试）用YOLOv10训练和 YOLOv8训练，最后的Best 显示，YOLOv8比 YOLOv10要好？？？
2. 所有参数都是用默认的；
3. 都是用的官网 nano 版本作为 pretrained 。

**Comment by wangqiqi** [comment]
数据集是私有定制的数据集，不是公开的数据集；
数据集中目标的尺寸变化范围比较大。

**Comment by jameslahm** [comment]
您好，感谢您的关注！您好，我们想确认一下您的训练环境是一致的吗？是都基于这个代码库训练YOLOv8和YOLOv10的吗？另一方面，您方便看下这个https://github.com/THU-MIG/yolov10/issues/111#issuecomment-2137277092 是否有帮助吗？谢谢！～

**Comment by wangqiqi** [comment]
训练环境是一致的，YOLOv10的环境是从 YOLOv8 拷贝迁移过来的。环境和数据都是一样的，只有模型不一样。哦，对了，YOLOv8的版本是 8.2.22（pip 升级后的）
YOLOv10的版本是 8.1.34（官网Clone YOLOv10）
所有的超参数都是用默认的，没有改变。预训练模型也都是用官网提供的。

**Comment by nobody-cheng** [comment]
或许应该都吧val结果保存下来**--save-json True **, 然后都用这个结果使用cocoapi进行验证比对

**Comment by wangqiqi** [comment]
> 或许应该都吧val结果保存下来**--save-json True **, 然后都用这个结果使用cocoapi进行验证比对

https://github.com/THU-MIG/yolov10/issues/100#issue-2320343475
https://github.com/THU-MIG/yolov10/issues/111#issuecomment-2138991593

有可能是定制数据集里小目标比较多的原因吧？？？

**Comment by jameslahm** [comment]
> > 或许应该都吧val结果保存下来**--save-json True **, 然后都用这个结果使用cocoapi进行验证比对
> 
> 
> 
> https://github.com/THU-MIG/yolov10/issues/100#issue-2320343475
> 
> https://github.com/THU-MIG/yolov10/issues/111#issuecomment-2138991593
> 
> 
> 
> 有可能是定制数据集里小目标比较多的原因吧？？？

您好，关于小目标请您看一下#136，您的测试评估方式跟阈值有关吗？

**Comment by jameslahm** [comment]
Please feel free to reopen this issue if you have further questions.
