### ISSUE TITLE
yolov10 导出onnx维度不对，且自己训练的pt推理时出错

### ISSUE THREAD

**Issue by cos888888** [THU-MIG/yolov10#149]
1. yolov10 导出onnx，output是[1,300,6]，6这个维度明显不对，coco 80类怎么说也不可能是6维，rt-detr导出是[1,300,84]，维度是对的。v1.1和master都测试了，都有这问题
2. yolov10自己的yolov10s.pt可以正常推理，但自己训练的pt在predict时候说dict没有shape属性，错在opy.py里非极大值抑制里。v1.1和master都测试了，都有这问题

**Comment by jameslahm** [comment]
感谢您的关注！
1. 您好，导出的onnx默认是端到端的，会输出最终预测的box坐标，标签和置信度分数，因此没有80类中每个类的预测概率，具体输出格式您可以参考#7。
2. 您好，因为现在使用命令行时会根据文件名里是否有v10来判断是否用YOLOv10的模型，您可以把pt文件重命名为带yolov10名字的pt文件，或者您可以使用python api调用方式来进行predict，如
```
from ultralytics import YOLOv10
model = YOLOv10("best.pt")
model.predict(...)
```

**Comment by cos888888** [comment]
> 感谢您的关注！
> 
> 1. 您好，导出的onnx默认是端到端的，会输出最终预测的box坐标，标签和置信度分数，因此没有80类中每个类的预测概率，具体输出格式您可以参考[如何理解模型输出output0：1 300 6 #7](https://github.com/THU-MIG/yolov10/issues/7)。
> 2. 您好，因为现在使用命令行时会根据文件名里是否有v10来判断是否用YOLOv10的模型，您可以把pt文件重命名为带yolov10名字的pt文件，或者您可以使用python api调用方式来进行predict，如
> 
> ```
> from ultralytics import YOLOv10
> model = YOLOv10("best.pt")
> model.predict(...)
> ```

thank you for your reply, I should write questions in English for your understanding. sorry

**Comment by jameslahm** [comment]
No worries. ❤️
