### ISSUE TITLE
PytorchStreamReader failed reading zip archive: failed finding central directory

### ISSUE THREAD

**Issue by Mr-lixiaoyao** [THU-MIG/yolov10#154]
![1](https://github.com/THU-MIG/yolov10/assets/79897103/0e6dbe68-a2a8-4f2e-8343-23cb764f5139)

**Comment by jameslahm** [comment]
Thanks for your interest! Is the checkpoint file correctly downloaded?

**Comment by jameslahm** [comment]
Please feel free to reopen this issue if you have further questions.
