### ISSUE TITLE
YOLOv10 output class and regression num

### ISSUE THREAD

**Issue by cdy-for-grad** [THU-MIG/yolov10#159]
https://github.com/THU-MIG/yolov10/blob/359435324913b4abeda7697142ae5cbf3c3b5e72/ultralytics/nn/modules/head.py#L506

great Job!
In this line, regression class could equal to number of class? 
Have you change the number in other code, or use x = x[:4] code?

thx

**Comment by jameslahm** [comment]
Thanks for your interest! This is the classification head rather than the regression head.
