### ISSUE TITLE
Inference output processing

### ISSUE THREAD

**Issue by ac2522** [THU-MIG/yolov10#163]
This is happening to me within C++ and Python, so I'm assuming this isn't a coding error, more likely a problem with my understanding. When looking at the output of inferences, there are values of width and height greater than 480 (my imgsz value) and negative values of x and y.

If I run inference with:
`!yolo predict model=runs/detect/yolov10x/weights/yolov10x.onnx imgsz=480 source='test3.jpg'`
Then I get the right answer:
![test3](https://github.com/THU-MIG/yolov10/assets/52031988/af12a7eb-0a26-4176-b619-dd367d7c03a4)

But running it manually with Python: 
```
import onnxruntime as ort
import numpy as np
import cv2
import matplotlib.pyplot as plt

# Load the ONNX model
session = ort.InferenceSession('runs/detect/yolov10x/weights/yolov10x.onnx')

# Load and preprocess the image
image = cv2.imread('test3.jpg')
input_image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

# Assuming the model expects a certain input size
input_tensor = input_image.astype(np.float32) / 255.0
input_tensor = input_tensor.transpose(2, 0, 1)  # Change to channel-first format
input_tensor = np.expand_dims(input_tensor, axis=0)

# Run the model
inputs = {session.get_inputs()[0].name: input_tensor}
outputs = session.run(None, inputs)

# Process the output
output = outputs[0]  # Assuming the output is [1, 300, 6]

# Extract bounding boxes and probabilities
boxes = output[0, :, :4]
probabilities = output[0, :, 4]

# Find the box with the highest probability
max_prob_index = np.argmax(probabilities)
x, y, w, h = boxes[max_prob_index]

# Draw rectangle on the image
start_point = (int(x), int(y))
end_point = (int(x + w), int(y + h))
output_image = cv2.rectangle(image.copy(), start_point, end_point, color, 1)

# Display the image using matplotlib
plt.imshow(cv2.cvtColor(output_image, cv2.COLOR_BGR2RGB))
plt.axis('off')
plt.show()
```
I get something bizarre, the x and y could be correct, but I don't know where the width and height have come from...?
![download](https://github.com/THU-MIG/yolov10/assets/52031988/d25fbbf9-45e0-4b18-9de9-e860dfa740cf)

Any help would be appreciated, I know that this isn't an issue with yolov10, but with ym own incompetence, thanks!

**Comment by ac2522** [comment]
Same occurs with my c++: 
```
    	for (int i = 0; i < num_array; ++i) {
			const int basic_pos = i * 6;

			float box_objectness = feat_ptr[basic_pos + 4];

			if (box_objectness > prob_threshold) {
				obs_log(LOG_INFO, "new: score? and x: %f, %f", box_objectness, feat_ptr[basic_pos]);
				float x_center = feat_ptr[basic_pos];
				float y_center = feat_ptr[basic_pos + 1];
				float w = feat_ptr[basic_pos + 2];
				float h = feat_ptr[basic_pos + 3];
				float x0 = x_center - w * 0.5f;
				float y0 = y_center - h * 0.5f;

				Object obj;
				obj.rect.x = x0;
				obj.rect.y = y0;
				obj.rect.width = w;
				obj.rect.height = h;
				obj.label = 0;
				obj.prob = box_objectness;
				objects.push_back(obj);
			}
		}
	}
```

**Comment by jameslahm** [comment]
Thanks for your interest! The format of output box is `xyxy` rather than `xywh`.

**Comment by ac2522** [comment]
Thank you, and apologies for the dumb question...

**Comment by 22wei22** [comment]
> Thanks for your interest! The format of output box is `xyxy` rather than `

> Thanks for your interest! The format of output box is `xyxy` rather than `xywh`.

where is the code? the onnx ouput is xyxy
