### ISSUE TITLE
Parameter Discrepancy in Yolov10n

### ISSUE THREAD

**Issue by V1ad20** [THU-MIG/yolov10#164]
Hello,

I noticed that my parameter count for YoloV10n is around 2.7M rather than the 2.3M showed in the repo.  I looked at issue #13 and it seems the reason is because there are parameters being counted which are not used in inference.

My first question is regarding clarification. If these extra parameters are not used in inference, does this mean these parameters are not directly used in calculating validation and test accuracy?

My second question is getting a little more guidance in how to remove these parameters.  I’m still a little confused on how to do this - would it be possible to provide the places where to modify the code?

Thank you so much!

**Comment by jameslahm** [comment]
Thanks for your interest! Does the issue #178 help?

**Comment by jameslahm** [comment]
Please feel free to reopen this issue if you have further questions.
