### ISSUE TITLE
训练的模型无法预测

### ISSUE THREAD

**Issue by NewerZeus** [THU-MIG/yolov10#166]
预测的语句是`yolo predict model=best.pt source='D:/blade/5.28/5.28/raw_bad_img/P2024-05-28-14-54-22-970.bmp'`，给出的报错`File "F:\project\yolov10-main\yolov10-main\ultralytics\utils\ops.py", line 217, in non_max_suppression
    bs = prediction.shape[0]  # batch size
AttributeError: 'dict' object has no attribute 'shape'`似乎某个变量的类型应该是torch.Tensor却变成了字典类型，导致没有属性。请问这个问题应该怎么解决或者是我训练的模型有什么问题吗？万分感谢

**Comment by jameslahm** [comment]
感谢您的关注！您可以参考一下这个#46~

**Comment by cos888888** [comment]
不能在命令行这么用，写代码进行推导，我把我代码粘贴上来，你自己参考下。
def main(onnx_model, input_img_dir, save_dir, cof_thresh = 0.21):
    
    test_sz = 1440

    session = ort.InferenceSession(onnx_model, providers=['CUDAExecutionProvider', 'CPUExecutionProvider'])

    model_inputs = session.get_inputs()

    total_jpg = os.listdir(input_img_dir)

    num_img = len(total_jpg)

    txt_green_num = 0
    txt_red_num = 0
    txt_yellow_num = 0
    txt_blue_num = 0

    #位置,类别都正确的数量
    det_green_num = 0
    det_red_num = 0
    det_yellow_num = 0
    det_blue_num = 0

    #内部映射关系
    custom_map = {'green':0,'red':1,'blue':2,'yellow':3,'hd-light':4}

    element_num = len(custom_map)

    #位置对,类别错数量
    err_cls_mat = np.zeros([element_num,element_num], np.float64)

    #位置错(漏检)
    err_miss_mat = np.zeros([element_num], np.float64)

    for i in range(num_img):
        jpg_name = total_jpg[i]
        pure_name = jpg_name[:-4]
        full_img_path = os.path.join(input_img_dir, jpg_name)
        #txt_name = pure_name + ".txt"
        #full_txt_path = os.path.join(input_txt_dir, txt_name)
        #yolov8预处理
        original_image = cv2.imread(full_img_path)
        
        [height, width, _] = original_image.shape
        length = max((height, width))
        image = np.zeros((length, length, 3), np.uint8)
        image[0:height, 0:width] = original_image
        
        scale = length / test_sz
        
        blob = cv2.dnn.blobFromImage(image, scalefactor=1 / 255, size=(test_sz, test_sz), swapRB=True)

        #做前向推理
        outputs = session.run(None, {model_inputs[0].name: blob})

        #修改写法
        outputs = np.squeeze(outputs[0], axis=0)

        rows = outputs.shape[0]

        #放当前图像所有检测结果
        detections = []
        txt_detections = []

        boxes = []
        scores = []
        class_ids = []

        for j in range(rows):
            
            out_conf = outputs[j,4]
            out_id = int(outputs[j,5])
            
            if out_conf > cof_thresh:
                
                x1 = int(outputs[j,0] * scale)
                y1 = int(outputs[j,1] * scale)
                
                x2 = int(outputs[j,2] * scale)
                y2 = int(outputs[j,3] * scale)
                
                draw_bounding_box(original_image, out_id, out_conf, x1, y1, x2, y2)
        
        save_full_path = os.path.join(save_dir, jpg_name)
        
        #保存一个测试结果图像
        cv2.imwrite(save_full_path, original_image)
        
        print("{} 图像处理完毕\n".format(i))

    return

**Comment by cos888888** [comment]
def main(onnx_model, input_img_dir, save_dir, cof_thresh = 0.21):
    
    test_sz = 1440

    session = ort.InferenceSession(onnx_model, providers=['CUDAExecutionProvider', 'CPUExecutionProvider'])

    model_inputs = session.get_inputs()

    total_jpg = os.listdir(input_img_dir)

    num_img = len(total_jpg)

    txt_green_num = 0
    txt_red_num = 0
    txt_yellow_num = 0
    txt_blue_num = 0

    #位置,类别都正确的数量
    det_green_num = 0
    det_red_num = 0
    det_yellow_num = 0
    det_blue_num = 0

    #内部映射关系
    custom_map = {'green':0,'red':1,'blue':2,'yellow':3,'hd-light':4}

    element_num = len(custom_map)

    #位置对,类别错数量
    err_cls_mat = np.zeros([element_num,element_num], np.float64)

    #位置错(漏检)
    err_miss_mat = np.zeros([element_num], np.float64)

    for i in range(num_img):
        jpg_name = total_jpg[i]
        pure_name = jpg_name[:-4]
        full_img_path = os.path.join(input_img_dir, jpg_name)
        #txt_name = pure_name + ".txt"
        #full_txt_path = os.path.join(input_txt_dir, txt_name)
        #yolov8预处理
        original_image = cv2.imread(full_img_path)
        
        [height, width, _] = original_image.shape
        length = max((height, width))
        image = np.zeros((length, length, 3), np.uint8)
        image[0:height, 0:width] = original_image
        
        scale = length / test_sz
        
        blob = cv2.dnn.blobFromImage(image, scalefactor=1 / 255, size=(test_sz, test_sz), swapRB=True)

        #做前向推理
        outputs = session.run(None, {model_inputs[0].name: blob})

        #修改写法
        outputs = np.squeeze(outputs[0], axis=0)

        rows = outputs.shape[0]

        #放当前图像所有检测结果
        detections = []
        txt_detections = []

        boxes = []
        scores = []
        class_ids = []

        for j in range(rows):
            
            out_conf = outputs[j,4]
            out_id = int(outputs[j,5])
            
            if out_conf > cof_thresh:
                
                x1 = int(outputs[j,0] * scale)
                y1 = int(outputs[j,1] * scale)
                
                x2 = int(outputs[j,2] * scale)
                y2 = int(outputs[j,3] * scale)
                
                draw_bounding_box(original_image, out_id, out_conf, x1, y1, x2, y2)
        
        save_full_path = os.path.join(save_dir, jpg_name)
        
        #保存一个测试结果图像
        cv2.imwrite(save_full_path, original_image)
        
        print("{} 图像处理完毕\n".format(i))

    return

**Comment by cos888888** [comment]
> 预测的语句是`yolo predict model=best.pt source='D:/blade/5.28/5.28/raw_bad_img/P2024-05-28-14-54-22-970.bmp'`，给出的报错`File "F:\project\yolov10-main\yolov10-main\ultralytics\utils\ops.py", line 217, in non_max_suppression bs = prediction.shape[0] # batch size AttributeError: 'dict' object has no attribute 'shape'`似乎某个变量的类型应该是torch.Tensor却变成了字典类型，导致没有属性。请问这个问题应该怎么解决或者是我训练的模型有什么问题吗？万分感谢

参考我上面代码

**Comment by jameslahm** [comment]
我们把YOLOv10设为命令行中的默认配置了。您方便更新代码再试一次吗？谢谢！

**Comment by jameslahm** [comment]
Please feel free to reopen this issue if you have further questions.
