### ISSUE TITLE
Why is validation performed every 10 epochs during training?

### ISSUE THREAD

**Issue by AAA1232** [THU-MIG/yolov10#17]
During training, it is noticed that validation is performed every 10 epochs. How can we perform validation after each epoch of training?
![QQ图片20240524223414](https://github.com/THU-MIG/yolov10/assets/134189733/a9311f3b-74ff-4c34-89b8-656ce98e12d9)

**Comment by lkxxxxx** [comment]
@AAA1232 
配置文件中的这个参数
![image](https://github.com/THU-MIG/yolov10/assets/101586594/789ace94-d185-4a3d-b753-3487f43ff142)

**Comment by AAA1232** [comment]
感谢，确实是这里
