### ISSUE TITLE
export  onnx error 

### ISSUE THREAD

**Issue by lmx-2021** [THU-MIG/yolov10#170]
ONNX: export failure ❌ 7.5s: Exporting the operator amax to ONNX opset version 12 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub

**Comment by jameslahm** [comment]
感谢您的关注！您可以尝试指定`opset=13`进行导出~

**Comment by lmx-2021** [comment]
same error, I have tried

**Comment by lmx-2021** [comment]
是不是因为我的torch版本比官方的低啊，因为cuda的驱动装不了那么高的torch 版本

**Comment by lmx-2021** [comment]
ONNX: export failure ❌ 2.9s: Exporting the operator amax to ONNX opset version 13 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub

**Comment by lmx-2021** [comment]
covered,environment error

**Comment by Zasa-Y** [comment]
> covered,environment error

Hello, can I ask what exactly is the environmental issue? I'm getting the same error.

**Comment by lmx-2021** [comment]
enverionmental problem

---- Replied Message ----
| From | ***@***.***> |
| Date | 07/29/2024 18:58 |
| To | THU-MIG/yolov10 ***@***.***> |
| Cc | lmx-2021 ***@***.***>,
State ***@***.***> |
| Subject | Re: [THU-MIG/yolov10] export onnx error (Issue #170) |

covered,environment error

Hello, can I ask what exactly is the environmental issue? I'm getting the same error.

**Comment by Zasa-Y** [comment]
> enverionmental problem
> […](#)
> ---- Replied Message ---- | From | ***@***.***> | | Date | 07/29/2024 18:58 | | To | THU-MIG/yolov10 ***@***.***> | | Cc | lmx-2021 ***@***.***>, State ***@***.***> | | Subject | Re: [THU-MIG/yolov10] export onnx error (Issue #170) | covered,environment error Hello, can I ask what exactly is the environmental issue? I'm getting the same error. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***>

Thank you, I encountered this issue on the Windows platform and it was resolved by transferring to the Ubuntu platform.
