### ISSUE TITLE
change imgsz to [height,width],while mosaic4 function cause problem

### ISSUE THREAD

**Issue by lmx-2021** [THU-MIG/yolov10#173]
height is not the same with width,how do I change def mosaic4(self, labels) in augment.py

def _mosaic4(self, labels):
        """Create a 2x2 image mosaic."""
        mosaic_labels = []
        s = self.imgsz
        yc, xc = (int(random.uniform(-x, 2 * s + x)) for x in self.border)  # mosaic center x, y
        for i in range(4):
            labels_patch = labels if i == 0 else labels["mix_labels"][i - 1]
            # Load image
            img = labels_patch["img"]
            h, w = labels_patch.pop("resized_shape")

            # Place img in img4
            if i == 0:  # top left
                img4 = np.full((s * 2, s * 2, img.shape[2]), 114, dtype=np.uint8)  # base image with 4 tiles
                x1a, y1a, x2a, y2a = max(xc - w, 0), max(yc - h, 0), xc, yc  # xmin, ymin, xmax, ymax (large image)
                x1b, y1b, x2b, y2b = w - (x2a - x1a), h - (y2a - y1a), w, h  # xmin, ymin, xmax, ymax (small image)
            elif i == 1:  # top right
                x1a, y1a, x2a, y2a = xc, max(yc - h, 0), min(xc + w, s * 2), yc
                x1b, y1b, x2b, y2b = 0, h - (y2a - y1a), min(w, x2a - x1a), h
            elif i == 2:  # bottom left
                x1a, y1a, x2a, y2a = max(xc - w, 0), yc, xc, min(s * 2, yc + h)
                x1b, y1b, x2b, y2b = w - (x2a - x1a), 0, w, min(y2a - y1a, h)
            elif i == 3:  # bottom right
                x1a, y1a, x2a, y2a = xc, yc, min(xc + w, s * 2), min(s * 2, yc + h)
                x1b, y1b, x2b, y2b = 0, 0, min(w, x2a - x1a), min(y2a - y1a, h)

            img4[y1a:y2a, x1a:x2a] = img[y1b:y2b, x1b:x2b]  # img4[ymin:ymax, xmin:xmax]
            padw = x1a - x1b
            padh = y1a - y1b

            labels_patch = self._update_labels(labels_patch, padw, padh)
            mosaic_labels.append(labels_patch)
        final_labels = self._cat_labels(mosaic_labels)
        final_labels["img"] = img4
        return final_labels

**Comment by ZeroCodePro** [comment]
How to change the definition of mosaic4 with one imgsz to [height,width]？

**Comment by lmx-2021** [comment]
Redefine the class of whole mosaic

---- Replied Message ----
| From | ***@***.***> |
| Date | 07/29/2024 10:35 |
| To | THU-MIG/yolov10 ***@***.***> |
| Cc | lmx-2021 ***@***.***>,
State ***@***.***> |
| Subject | Re: [THU-MIG/yolov10] change imgsz to [height,width],while mosaic4 function cause problem (Issue #173) |

How to change the definition of mosaic4 with one imgsz to [height,width]？

**Comment by ZeroCodePro** [comment]
Could you please provide the modified mosaic? Thank you very much!
