### ISSUE TITLE
Questions about the inconsistency between the experimental results of YOLOv10-N parameters and FLOPs and the description in the article.

### ISSUE THREAD

**Issue by Hy87380510** [THU-MIG/yolov10#177]
Hello, I have some questions about the parameters and FLOPs data of the YOLOv10-N model you mentioned in your article. According to the data you provided, the parameter size is 2.3M and FLOPs are 6.7G. However, in my experiments, the parameter amount of the model reached 2.7M, and the FLOPs were 8.4G. What is the reason for this difference? Can you provide some additional information? Thank you very much for your time and help!

**Comment by Hy87380510** [comment]
![Uploading image.png…]()

**Comment by Hy87380510** [comment]
Hello, I have some questions about the parameters and FLOPs data of the YOLOv10-N model you mentioned in your article. According to the data you provided, the parameter size is 2.3M and FLOPs are 6.7G. However, in my experiments, the parameter amount of the model reached 2.7M, and the FLOPs were 8.4G. What is the reason for this difference? Can you provide some additional information? Thank you very much for your time and help!
![image](https://github.com/THU-MIG/yolov10/assets/157335035/6f63aad4-9b22-4492-be33-a282b963f009)

**Comment by jameslahm** [comment]
Thanks for your interest! Does the issue #178 help?
