### ISSUE TITLE
关于one2one 和one2manay 的Consistent Matching Metric

### ISSUE THREAD

**Issue by lkxxxxx** [THU-MIG/yolov10#18]
有关one2one和one2many的问题
请问在模型中训练的时候是对one2many中预测的目标进行损失计算，然后将最好的预测结果权重共享给one2one吗？
然后再模型部署推理的时候只使用one2one。
还有就是论文中有关Consistent Matching Metric的证明是说明one2one的预测与one2many的最佳预测是相等的吗？
非常感谢大佬解答

**Comment by jameslahm** [comment]
非常感谢您的关注！您好，是这样的～

> 有关one2one和one2many的问题 请问在模型中训练的时候是对one2many中预测的目标进行损失计算，然后将最好的预测结果权重共享给one2one吗？ 然后再模型部署推理的时候只使用one2one。 还有就是论文中有关Consistent Matching Metric的证明是说明one2one的预测与one2many的最佳预测是相等的吗？ 非常感谢大佬解答
