### ISSUE TITLE
TypeError: YOLOv10.init_subclass() takes no keyword arguments

### ISSUE THREAD

**Issue by RedHeartSecretMan** [THU-MIG/yolov10#180]
**Description:**
I'm encountering a TypeError when defining a class YOLOv10 that inherits from Model and PyTorchModelHubMixin. The error message is TypeError: YOLOv10.__init_subclass__() takes no keyword arguments.

**Code Example:**
Here's the code that produces the error:

```
from ultralytics.engine.model import Model
from ultralytics.nn.tasks import YOLOv10DetectionModel
from .val import YOLOv10DetectionValidator
from .predict import YOLOv10DetectionPredictor
from .train import YOLOv10DetectionTrainer

from huggingface_hub import PyTorchModelHubMixin

class YOLOv10(Model, PyTorchModelHubMixin, library_name="ultralytics", repo_url="https://github.com/THU-MIG/yolov10", tags=["object-detection", "yolov10"]):

    def __init__(self, model="yolov10n.pt", task=None, verbose=False, names=None):
        super().__init__(model=model, task=task, verbose=verbose)
        if names is not None:
            setattr(self.model, 'names', names)

    def push_to_hub(self, repo_name, **kwargs):
        config = kwargs.get('config', {})
        config['names'] = self.names
        config['model'] = self.model.yaml['yaml_file']
        config['task'] = self.task
        kwargs['config'] = config
        super().push_to_hub(repo_name, **kwargs)

    @property
    def task_map(self):
        """Map head to model, trainer, validator, and predictor classes."""
        return {
            "detect": {
                "model": YOLOv10DetectionModel,
                "trainer": YOLOv10DetectionTrainer,
                "validator": YOLOv10DetectionValidator,
                "predictor": YOLOv10DetectionPredictor,
            },
        }

```

**Error Message:**
```
Traceback (most recent call last):
  File ".conda/envs/tensor/bin/yolo", line 5, in <module>
    from ultralytics.cfg import entrypoint
  File "yolov10/ultralytics/__init__.py", line 5, in <module>
    from ultralytics.data.explorer.explorer import Explorer
  File "yolov10/ultralytics/data/explorer/explorer.py", line 18, in <module>
    from ultralytics.models.yolo.model import YOLO
  File "yolov10/ultralytics/models/__init__.py", line 6, in <module>
    from .yolov10 import YOLOv10
  File "yolov10/ultralytics/models/yolov10/__init__.py", line 1, in <module>
    from .model import YOLOv10
  File "yolov10/ultralytics/models/yolov10/model.py", line 9, in <module>
    class YOLOv10(Model, PyTorchModelHubMixin, library_name="ultralytics", repo_url="https://github.com/THU-MIG/yolov10", tags=["object-detection", "yolov10"]):
TypeError: YOLOv10.__init_subclass__() takes no keyword arguments
```

**Steps to Reproduce:**
Define the class YOLOv10 as shown in the code example.
Run the script containing this class definition.

**Expected Behavior:**
The class should be defined without any TypeError.

**Actual Behavior:**
A TypeError is raised, indicating that YOLOv10.__init_subclass__() does not accept keyword arguments.

**Additional Context:**
It seems that keyword arguments cannot be passed during class definition. I need a way to correctly initialize these parameters in the class definition or constructor.

**Possible Solution:**
From my understanding, the parameters like library_name, repo_url, and tags should be handled within the class itself rather than during its definition. I would appreciate guidance on the correct approach to initialize these parameters.

**Comment by vinhnguyen21** [comment]
I think it relates to torch version (< 2.x). you can try:
`class YOLOv10(Model):` instead of `class YOLOv10(Model, PyTorchModelHubMixin, library_name="ultralytics", repo_url="https://github.com/THU-MIG/yolov10", tags=["object-detection", "yolov10"]):
` for quick testing.

**Comment by RedHeartSecretMan** [comment]
Thanks for your reply! In Python, you cannot pass keyword arguments directly in the class definition. So I'm not sure how the official code works.

**Comment by kevin-hxq** [comment]
remove parameters  library_name="ultralytics", repo_url="https://github.com/THU-MIG/yolov10", tags=["object-detection", "yolov10"],it works.

**Comment by midasklr** [comment]
`conda create -n yolov10 python=3.9
conda activate yolov10
pip install -r requirements.txt
pip install -e .`

and than:
`python app.py
`

**Comment by Franfee** [comment]
> I think it relates to torch version (< 2.x). you can try: `class YOLOv10(Model):` instead of `class YOLOv10(Model, PyTorchModelHubMixin, library_name="ultralytics", repo_url="https://github.com/THU-MIG/yolov10", tags=["object-detection", "yolov10"]): ` for quick testing.

thanks，it works！

**Comment by leonnil** [comment]
I suppose this problem may be related to the Python version. Which Python version are you using? You can update your Python version to 3.9 and try again.

**Comment by RedHeartSecretMan** [comment]
Hi, I've reverted the PyTorch version to 2.0.1, and the official examples indeed run correctly without needing any source code modifications. However, I'm still puzzled about the issue I encountered earlier.

In my limited experience with Python programming, I've never seen the use of keyword arguments immediately following the class keyword during class definition. My understanding is that the class definition process typically only involves class inheritance. Could you provide some clarification or insights into this? Thank you!

**Comment by jameslahm** [comment]
Please feel free to reopen this issue if you have further questions.

**Comment by deppmish2** [comment]
I have same error, using python 3.12.1 and pytorch 2.3.1

**Comment by devbharat** [comment]
I have the same problem in this runtime https://huggingface.co/docs/inference-endpoints/en/others/runtime

**Comment by vishwapatill** [comment]
Updating the huggingface-hub  worked for me 

pip install huggingface-hub --upgrade .

also make sure to have numpy-1.26.0  

Followed:
https://github.com/ZhengPeng7/BiRefNet/issues/38#issuecomment-2331015814
