### ISSUE TITLE
ONNX evaluation on custom data

### ISSUE THREAD

**Issue by sulaiman1988** [THU-MIG/yolov10#181]
The error occurs when trying to evaluate the ONNX model by this command"yolo val task=detect model=best.onnx imgsz=640 data=custom_data.yaml":
yolov10/ultralytics/utils/metrics.py", line 366, in process_batch
self.matrix[detection_classes[m1[j]], gc] += 1  # correct
IndexError: index 227 is out of bounds for axis 0 with size 7

**Comment by sanha9999** [comment]
Can you check the "nc" parameter or class index in the "custom_data.yaml" file matches the number of classes in the "best.onnx" model?

**Comment by sulaiman1988** [comment]
The nc parameter equals 6

**Comment by sulaiman1988** [comment]
when print out prediction.shape, nc 
torch.Size([1, 300, 6])
bs 1
nc 296
tensor([[[ 4.2046e+02,  4.2621e+02,  6.4042e+02,  4.9574e+02,  5.7271e-01,  0.0000e+00],
         [ 3.4320e+02,  4.2374e+02,  4.2045e+02,  4.6300e+02,  4.3027e-01,  0.0000e+00],
         [ 3.4374e+02,  4.2300e+02,  4.6362e+02,  4.7450e+02,  2.5837e-01,  0.0000e+00],
         ...,
         [ 4.5499e+02,  3.4717e+02,  5.3298e+02,  4.0917e+02,  4.9472e-06,  3.0000e+00],
         [ 4.6237e+02,  5.6022e+02,  6.3736e+02,  6.3166e+02,  4.9472e-06,  2.0000e+00],
         [-7.5188e-01,  6.0991e+02,  7.6541e+01,  6.4117e+02,  4.9174e-06,  3.0000e+00]]], device='cuda:0')
   so how how can I return just one prediction not 300

**Comment by sanha9999** [comment]
Would you please use "v10postprocess" function located at "/ultralytics/utils/ops.py " instead of NMS?

**Comment by sulaiman1988** [comment]
should I update the nc from 80 to my class which is 6 in def v10postprocess

**Comment by sulaiman1988** [comment]
The error is still as is if I use nc =80 or nc = 6

**Comment by sanha9999** [comment]
Is the "best.onnx" model trained using "custom_data.yaml"?

**Comment by sulaiman1988** [comment]
I convert best.pt into best.onnx and best.pt is trained using custom_data.yaml
conversion occurs using command "yolo export model=runs/detect/yolos_train/weights/best.pt  format=onnx opset=13 simplify"

**Comment by sulaiman1988** [comment]
conversion

PyTorch: starting from 'runs/detect/yolos_train/weights/best.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 300, 6) (5.5 MB)

ONNX: starting export with onnx 1.14.0 opset 13...
============= Diagnostic Run torch.onnx.export version 2.0.1+cu117 =============
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

ONNX: simplifying with onnxsim 0.4.36...
ONNX: export success ✅ 1.0s, saved as 'runs/detect/yolos_train/weights/best.onnx' (8.8 MB)

Export complete (2.5s)
Results saved to yolov10/runs/detect/yolos_train/weights
Predict:         yolo predict task=detect model=runs/detect/yolos_train/weights/best.onnx imgsz=640  
Validate:        yolo val task=detect model=runs/detect/yolos_train/weights/best.onnx imgsz=640 data=custom_data.yaml  
Visualize:       https://netron.app
💡 Learn more at https://docs.ultralytics.com/modes/export

**Comment by sanha9999** [comment]
> or update the codebase and try again. #184

update the yolov10 codebase and try onnx export, val again. 
There's a bug that doesn't recognize if the name doesn't have "yolov10".

**Comment by sulaiman1988** [comment]
still the same error  /yolov10/ultralytics/utils/ops.py", line 855, in v10postprocess
    assert(4 + nc == preds.shape[-1])
AssertionError

**Comment by sanha9999** [comment]
in "/ultralytics/models/yolov10/val.py"
change code
```python
class YOLOv10DetectionValidator(DetectionValidator):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.args.save_json |= self.is_coco

    def postprocess(self, preds):
        if isinstance(preds, dict):
            preds = preds["one2one"]

        if isinstance(preds, (list, tuple)):
            preds = preds[0]
    
        if preds.shape[-1] == 6:
            pass
        else:
            preds = preds.transpose(-1, -2)
            bboxes, scores, labels = ops.v10postprocess(preds, self.args.max_det, preds.shape[-1]-4)
            bboxes = ops.xywh2xyxy(bboxes)
            preds = torch.cat([bboxes, scores.unsqueeze(-1), labels.unsqueeze(-1)], dim=-1)
        
        return preds
```

**Comment by sulaiman1988** [comment]
Really thanks a lot

**Comment by sulaiman1988** [comment]
another question please what is the best way to update the codebase 
is it reinstall ? or there is specific command

**Comment by sanha9999** [comment]
As far as I know, we use a command like "git pull" to update it.

**Comment by leonnil** [comment]
I've fixed this in the codebase, pls update your code. Thanks for your contributions!

**Comment by jameslahm** [comment]
Please feel free to reopen this issue if you have further questions.

**Comment by MrWangg1992** [comment]
what is the output 300 stands for in output shape 1x300x6?

**Comment by syorami** [comment]
@leonnil hi I notice that in `postprocess` function there is no confidence filtering while in YOLOv8 the filtering is performed in nms process, which means that the `conf` argument is invalid in YOLOv10 evaluation. How can I modify the code so we can support confidence filtering?
