### ISSUE TITLE
Can I use YOLOv10 through Ultralytics v8.2 directly?

### ISSUE THREAD

**Issue by ProsperousYe** [THU-MIG/yolov10#182]
![image](https://github.com/THU-MIG/yolov10/assets/93996508/c7729609-e126-4bd9-8eeb-3ce9d3b583ba)
When I wanted to integrate YOLOv10 into my project, I tried to import YOLOv10 directly from Ultralytics, which is as described in the documentation, but it failed. Why is this? The version of Ultralytics I use is 8.2.28 as shown as follows:
![image](https://github.com/THU-MIG/yolov10/assets/93996508/576b335e-791d-4d65-a0c2-dacfb354c7fc)

**Comment by knoppmyth** [comment]
I believe the Ultralytics team is still working on incorporating v10. Keep an eye on their github for more details. BTW, you'd just import "YOLO" and specific a v10 model. Take a look [here](https://docs.ultralytics.com/models/yolov10).

**Comment by ProsperousYe** [comment]
Thanks a lot! I will keep an eye on Ultralytics' progress. It seems that the author reimplemented Ultralytics library to support their algorithm which have not been officially supported by Ultralyrics team.

**Comment by uttam-eigyo** [comment]
`"name": "AttributeError",
	"message": "Can't get attribute 'YOLOv10DetectionModel' on <module 'ultralytics.nn.tasks' from '/Users/uttamdwivedi/Desktop/codestuff/obj-detection/venv/lib/`
	
	@knoppmyth When I try to do the same as it is suggested in the link you shared, I get the error as mentioned above. 
	Any Idea?

**Comment by knoppmyth** [comment]
@uttam-eigyo As I stated, Ultralytics is still working on [this](https://github.com/ultralytics/ultralytics/pull/13113). If you want to use YOLOv10, follow the instructions [here](https://github.com/THU-MIG/yolov10#installation).
