### ISSUE TITLE
Issue with Resuming Training Process

### ISSUE THREAD

**Issue by bkpagen** [THU-MIG/yolov10#19]
If I want to resume training, is it correct to call it like this: "yolo detect train model=F:/01CODE/yolov10-main/runs/detect/train/weights/last.pt resume=True"?

**Comment by jameslahm** [comment]
Thanks for your interest! Yes, it is correct.
> If I want to resume training, is it correct to call it like this: "yolo detect train model=F:/01CODE/yolov10-main/runs/detect/train/weights/last.pt resume=True"?

**Comment by jameslahm** [comment]
Do you use `YOLO` create the model? Could you please try to replace `YOLO` with `YOLOv10`?

**Comment by bkpagen** [comment]
I just invoked "yolo detect train model=F:/01CODE/yolov10-main/runs/detect/train/weights/last.pt resume=True" in the terminal.

**Comment by jameslahm** [comment]
Thanks! We just fixed this issue. Could you please update the codebase and try again?
