### ISSUE TITLE
is the code ready ? i cant see detect.py

### ISSUE THREAD

**Issue by glennford49** [THU-MIG/yolov10#193]
any code for running this model on a video source or camera? i cant  find the detect.py

**Comment by sanha9999** [comment]
You can run it by referring to "ultralytics/engine/predictor.py ".
```
$ yolo mode=predict model=yolov10n.pt source=video.mp4
```

**Comment by jameslahm** [comment]
Thanks for your interest! Please feel free to reopen this issue if you have further questions.
