### ISSUE TITLE
Result names output indecies instead of the actual class name

### ISSUE THREAD

**Issue by mohamedlotfy50** [THU-MIG/yolov10#194]
I have downloaded the latest release using wget and after prediction I found that the result name contains indices not the class names as I used to, here is the steps that I have done:

```
!wget -P models -q https://github.com/jameslahm/yolov10/releases/download/v1.0/yolov10n.pt
```
```python
results = model(image,verbose=False)
print(results[0])
```
![image](https://github.com/THU-MIG/yolov10/assets/51348724/b6368cf4-414e-468f-af9c-deff0e4f4095)

**Comment by leonnil** [comment]
Thank you for your interest! According to the URL you provided, the model you downloaded is v1.0. Please download [v1.1](https://github.com/THU-MIG/yolov10/releases/tag/v1.1) and try again.

**Comment by mohamedlotfy50** [comment]
Thank you it worked after updating to version 1.1:

```
!wget -P models -q https://github.com/jameslahm/yolov10/releases/download/v1.1/yolov10n.pt
```
