### ISSUE TITLE
when val：AttributeError: 'dict' object has no attribute 'shape'

### ISSUE THREAD

**Issue by xingyli** [THU-MIG/yolov10#20]

**Comment by jameslahm** [comment]
Thanks for your interest! Could you please provide the details of how to reproduce this issue?

**Comment by xy3xy3** [comment]
```python
from ultralytics import YOLO

# Load a model
model = YOLO("models/yolov10n.pt").to("cuda")  # pretrained YOLOv8n model
print(model.names)
res = model.predict("bus.jpg",
                  show_boxes=True,show_conf=True,show_labels=True)[0]
res.show()
```

Same problem I meet.

```shell
root@xy3dn:~/yolo8# /root/.pyenv/versions/3.10.12/bin/python /root/yolo8/test.py
{0: '0', 1: '1', 2: '2', 3: '3', 4: '4', 5: '5', 6: '6', 7: '7', 8: '8', 9: '9', 10: '10', 11: '11', 12: '12', 13: '13', 14: '14', 15: '15', 16: '16', 17: '17', 18: '18', 19: '19', 20: '20', 21: '21', 22: '22', 23: '23', 24: '24', 25: '25', 26: '26', 27: '27', 28: '28', 29: '29', 30: '30', 31: '31', 32: '32', 33: '33', 34: '34', 35: '35', 36: '36', 37: '37', 38: '38', 39: '39', 40: '40', 41: '41', 42: '42', 43: '43', 44: '44', 45: '45', 46: '46', 47: '47', 48: '48', 49: '49', 50: '50', 51: '51', 52: '52', 53: '53', 54: '54', 55: '55', 56: '56', 57: '57', 58: '58', 59: '59', 60: '60', 61: '61', 62: '62', 63: '63', 64: '64', 65: '65', 66: '66', 67: '67', 68: '68', 69: '69', 70: '70', 71: '71', 72: '72', 73: '73', 74: '74', 75: '75', 76: '76', 77: '77', 78: '78', 79: '79'}

Traceback (most recent call last):
  File "/root/yolo8/test.py", line 6, in <module>
    res = model.predict("bus.jpg",
  File "/root/yolo8/ultralytics/engine/model.py", line 441, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "/root/yolo8/ultralytics/engine/predictor.py", line 168, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
  File "/root/.pyenv/versions/3.10.12/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/root/yolo8/ultralytics/engine/predictor.py", line 255, in stream_inference
    self.results = self.postprocess(preds, im, im0s)
  File "/root/yolo8/ultralytics/models/yolo/detect/predict.py", line 25, in postprocess
    preds = ops.non_max_suppression(
  File "/root/yolo8/ultralytics/utils/ops.py", line 216, in non_max_suppression
    bs = prediction.shape[0]  # batch size
AttributeError: 'dict' object has no attribute 'shape'
```

**Comment by ZZQ565697818** [comment]
> Thanks for your interest! Could you please provide the details of how to reproduce this issue?

I used to meet the same issue. After I got a trained weight，I wanted to use it to val.when I run the evaluate CLI command，the issue appears.

**Comment by xy3xy3** [comment]
> ```python
> from ultralytics import YOLO
> 
> # Load a model
> model = YOLO("models/yolov10n.pt").to("cuda")  # pretrained YOLOv8n model
> print(model.names)
> res = model.predict("bus.jpg",
>                   show_boxes=True,show_conf=True,show_labels=True)[0]
> res.show()
> ```
> 
> Same problem I meet.
> 
> ```shell
> root@xy3dn:~/yolo8# /root/.pyenv/versions/3.10.12/bin/python /root/yolo8/test.py
> {0: '0', 1: '1', 2: '2', 3: '3', 4: '4', 5: '5', 6: '6', 7: '7', 8: '8', 9: '9', 10: '10', 11: '11', 12: '12', 13: '13', 14: '14', 15: '15', 16: '16', 17: '17', 18: '18', 19: '19', 20: '20', 21: '21', 22: '22', 23: '23', 24: '24', 25: '25', 26: '26', 27: '27', 28: '28', 29: '29', 30: '30', 31: '31', 32: '32', 33: '33', 34: '34', 35: '35', 36: '36', 37: '37', 38: '38', 39: '39', 40: '40', 41: '41', 42: '42', 43: '43', 44: '44', 45: '45', 46: '46', 47: '47', 48: '48', 49: '49', 50: '50', 51: '51', 52: '52', 53: '53', 54: '54', 55: '55', 56: '56', 57: '57', 58: '58', 59: '59', 60: '60', 61: '61', 62: '62', 63: '63', 64: '64', 65: '65', 66: '66', 67: '67', 68: '68', 69: '69', 70: '70', 71: '71', 72: '72', 73: '73', 74: '74', 75: '75', 76: '76', 77: '77', 78: '78', 79: '79'}
> 
> Traceback (most recent call last):
>   File "/root/yolo8/test.py", line 6, in <module>
>     res = model.predict("bus.jpg",
>   File "/root/yolo8/ultralytics/engine/model.py", line 441, in predict
>     return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
>   File "/root/yolo8/ultralytics/engine/predictor.py", line 168, in __call__
>     return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
>   File "/root/.pyenv/versions/3.10.12/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
>     response = gen.send(None)
>   File "/root/yolo8/ultralytics/engine/predictor.py", line 255, in stream_inference
>     self.results = self.postprocess(preds, im, im0s)
>   File "/root/yolo8/ultralytics/models/yolo/detect/predict.py", line 25, in postprocess
>     preds = ops.non_max_suppression(
>   File "/root/yolo8/ultralytics/utils/ops.py", line 216, in non_max_suppression
>     bs = prediction.shape[0]  # batch size
> AttributeError: 'dict' object has no attribute 'shape'
> ```

This code can be run on YOLO V8.However,it can't work on v10.

**Comment by jameslahm** [comment]
Could you please try to replace `YOLO` with `YOLOv10`? like
```
YOLOv10("models/yolov10n.pt")
```

**Comment by xy3xy3** [comment]
> Could you please try to replace `YOLO` with `YOLOv10`? like
> 
> ```
> YOLOv10("models/yolov10n.pt")
> ```

```python
from ultralytics import YOLOv10

# Load a model
model = YOLOv10("models/yolov10n.pt").to("cuda")  # pretrained YOLOv8n model
print(model.names)
res = model.predict("bus.jpg",
                  show_boxes=True,show_conf=True,show_labels=True)[0]
res.show()
```
Thanks.It is working.

**Comment by xingyli** [comment]
> Thanks for your interest! Could you please provide the details of how to reproduce this issue?

when I run the val CLI command, the issue appears. I created a new environment according to the tutorial, but it was not resolved. Just now, I replaced yolo with yolov10 using the comment section val. py and it runs successfully. Thank!
