### ISSUE TITLE
how can i access all the bounding box?

### ISSUE THREAD

**Issue by glennford49** [THU-MIG/yolov10#206]
i want to extract the valid bounding box based on threshold result on , how can i extract it,

**Comment by leonnil** [comment]
Thank you for your interest! Please try setting `save=True` during validation or prediction. The detection results will be saved in a text file, following the format `[class] [x_center] [y_center] [width] [height]` in `runs/detect/predict/labels` by default.

**Comment by glennford49** [comment]
thanks, i have pictured it out, its on the predict.py

**Comment by jameslahm** [comment]
Please feel free to reopen this issue if you have further questions.
