### ISSUE TITLE
When running VisDrone with 100 epochs, the accuracy is not displayed for the first ten epochs. However, when set to 10 epochs, the accuracy is displayed.

### ISSUE THREAD

**Issue by magic524** [THU-MIG/yolov10#21]
I followed the steps to install and run YOLOv10 on an RTX 3090. When the number of epochs is set to 10, the accuracy is displayed, but when the number of epochs is set to 100, the accuracy is not displayed, and all accuracy results are 0.
![{4C3C39D4-D31C-43f7-8F8D-AF0407592BD4}](https://github.com/THU-MIG/yolov10/assets/99181308/bb4d5b84-449f-40ad-9487-6fd6c83ac5c1)
![126571b7-c8e5-4662-8568-15c11ff57905](https://github.com/THU-MIG/yolov10/assets/99181308/a19e80a9-2f16-48d7-8f96-8da26dac6071)
![Uploading {DFEFFBC8-43F2-4525-A550-2F1AF3352829}.png…]()

**Comment by jameslahm** [comment]
Thanks for your interest! Does this issue #17 help?
