### ISSUE TITLE
SyntaxError: 'evolve' is not a valid YOLO argument. 

### ISSUE THREAD

**Issue by lolongcovas** [THU-MIG/yolov10#228]
Just passing the `evolve` param to the command line to train the detector it raises this error.

**Comment by sanha9999** [comment]
could you tell me the command you CLI entered?

**Comment by lolongcovas** [comment]
```bash
yolo detect train data=coco8.yaml model=yolov10m.yaml epochs=500 batch=256 imgsz=640 device=0 evolve=True
```

**Comment by sanha9999** [comment]
https://docs.ultralytics.com/modes/train/#train-settings

As far as I know, Ultralytics was no option "evolve".
Is there a case where the "evolve" option is used in other YOLO versions?

**Comment by sanha9999** [comment]
https://github.com/ultralytics/ultralytics/issues/9007

It seems to be supported by "yolov5", but not by "yolov8(ultralytics)" library.

**Comment by lolongcovas** [comment]
I see, thanks!
