### ISSUE TITLE
RuntimeError: selected index k out of range

### ISSUE THREAD

**Issue by alatriste-lee** [THU-MIG/yolov10#23]
![WX20240525-032909@2x](https://github.com/THU-MIG/yolov10/assets/7877379/564a0a22-b031-4762-b774-ff7e066f4585)
win10，torch  1.10.1 ，  torchvision    0.11.2

**Comment by alatriste-lee** [comment]
有没有可能支持到imgsz=64？

**Comment by jameslahm** [comment]
Thanks for your interest! The reason may be that `max_det` is larger than the number of output predictions. Could you please try to reduce `max_det` in the default.yaml? like `max_det=10`.

**Comment by alatriste-lee** [comment]
imgsz=64 max_det=5确实避免了上一个问题，接下来检查预测结果出了新的问题

![WX20240525-173021@2x](https://github.com/THU-MIG/yolov10/assets/7877379/3add42ec-f441-4d57-a5f6-d267527d1207)

>  File "C:\Users\pc\workspace\yolov10\ultralytics\utils\ops.py", line 215, in non_max_suppression
>     bs = prediction.shape[0]  # batch size
> AttributeError: 'dict' object has no attribute 'shape'
> 

用的命令是 yolo predict model=runs\detect\train\weights\best.pt source=train_data\taotong\images imgsz=64 device=0

另：在imgsz=256时，最后给出的map截图是这样的：

![Uploading WX20240525-173556@2x.png…]()

**Comment by jameslahm** [comment]
您好，这个是因为checkpoint文件名里没有yolov10，没有使用YOLOv10创建模型。您可以将checkpoint重命名为含yolov10的文件名，或者使用YOLOv10创建模型，然后使用model.predict方法进行预测。
https://github.com/THU-MIG/yolov10/blob/f19f3e521f804c43d52112c32c887d5d8654b0ca/ultralytics/cfg/__init__.py#L553

**Comment by alatriste-lee** [comment]
> 您好，这个是因为checkpoint文件名里没有yolov10，没有使用YOLOv10创建模型。您可以将checkpoint重命名为含yolov10的文件名，或者使用YOLOv10创建模型，然后使用model.predict方法进行预测。
> 
> https://github.com/THU-MIG/yolov10/blob/f19f3e521f804c43d52112c32c887d5d8654b0ca/ultralytics/cfg/__init__.py#L553

多谢，我试一下

**Comment by littlestone0806** [comment]
训练默认开启了amp，就会默认调用yolov8n.pt造成这个问题，设置训练参数amp=False试试

**Comment by alatriste-lee** [comment]
> 您好，这个是因为checkpoint文件名里没有yolov10，没有使用YOLOv10创建模型。您可以将checkpoint重命名为含yolov10的文件名，或者使用YOLOv10创建模型，然后使用model.predict方法进行预测。
> 
> https://github.com/THU-MIG/yolov10/blob/f19f3e521f804c43d52112c32c887d5d8654b0ca/ultralytics/cfg/__init__.py#L553

把best.pt文件名改成yolov10best.pt之后，跑通了。

也许是我的数据集的问题，v10当imgsz=256时，对比yolov7当imgsz=128的效果，cpu预测单张慢了5ms多（当然v7默认给出的时间是inference+nms，不确定能否直接对比），然后数据集的开头有一张没预测出来，v7那边预测出来了。好消息是v10这边的预测框能更贴合目标，v7那边在用的时候需要手工扩大一点。

@jameslahm 有帮上忙的话我可以把这套图给到你。

**Comment by jameslahm** [comment]
感谢您的详细评估和帮助！由于我们目前资源有限，可能无法在您的数据集上进行测试评估，所以暂时用不到您的数据集，但还是很感谢！
