### ISSUE TITLE
YOLOv9 missing from the plot

### ISSUE THREAD

**Issue by Y-T-G** [THU-MIG/yolov10#25]
Hey, nice work.

But it seems there's no YOLOv9 in this plot.

![image](https://github.com/THU-MIG/yolov10/assets/32206511/9f2dc0aa-c2cc-4a9a-8c28-7204095b7925)

**Comment by jameslahm** [comment]
Thanks for your interest! YOLOv9-C is in the plot. Since YOLOv9 has not released the small models yet, we cannot measure their latency.
<img width="791" alt="image" src="https://github.com/THU-MIG/yolov10/assets/43805318/4289a015-8ada-432c-8038-59376e5649ff">

**Comment by Y-T-G** [comment]
@jameslahm Hmm, I see. But you also have YOLOv9-S and YOLOv9-M measured in the paper.

![image](https://github.com/THU-MIG/yolov10/assets/32206511/3e7244ca-8fb3-4e55-8e56-e078adc884c0)

**Comment by jameslahm** [comment]
Yes, these data of YOLOv9-S and YOLOv9-M are referred from the paper of YOLOv9. However, YOLOv9 has not released these models, so we cannot measure the latency of them.
