### ISSUE TITLE
about NMS

### ISSUE THREAD

**Issue by Freeman-Cai** [THU-MIG/yolov10#251]
I find the NMS code in **ultralytics/utils/ops.py** when I run model.predict(), and I want to know the correct method to get the ono2one result. Thx very much!!!

**Comment by leonnil** [comment]
Thank you for your interest! In YOLOv10, we don’t use NMS in post-processing. The predictions you get are directly from the one2one branch.
https://github.com/THU-MIG/yolov10/blob/36efe34fe1126a4ce639403f1ce16fa0edbc16fd/ultralytics/models/yolov10/predict.py#L8

**Comment by Freeman-Cai** [comment]
> Thank you for your interest! In YOLOv10, we don’t use NMS in post-processing. The predictions you get are directly from the one2one branch.
> 
> https://github.com/THU-MIG/yolov10/blob/36efe34fe1126a4ce639403f1ce16fa0edbc16fd/ultralytics/models/yolov10/predict.py#L8

Thank you for your reply! I find that I didn't pull the newest code resulted in this issue...
