### ISSUE TITLE
How to turn off albumentations?

### ISSUE THREAD

**Issue by Andy718811** [THU-MIG/yolov10#264]
How to turn off the albumentations methods that always used in yolov10?

Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01), CLAHE(p=0.01, clip_limit=(1, 4.0), tile_grid_size=(8, 8))

**Comment by leonnil** [comment]
Thank you for your interest! I think you can just run `pip uninstall albumentations`, or try annotating the code here:
https://github.com/THU-MIG/yolov10/blob/2c36ab0f108efdd17c7e290564bb845ccb6844d8/ultralytics/data/augment.py#L1002

**Comment by Andy718811** [comment]
Thank you so much for your reply, it worked well.
