### ISSUE TITLE
why the map is always 0

### ISSUE THREAD

**Issue by Anchovy0901** [THU-MIG/yolov10#28]
![Snipaste_2024-05-25_09-56-30](https://github.com/THU-MIG/yolov10/assets/70782318/cefe31d6-81a7-4a63-bf07-a333a41e3682)

**Comment by jameslahm** [comment]
Thanks for your interest! Does this issue #17 help? Besides, we just updated the codebase with `val_period=1` in default.yaml. Could you please update the codebase and try again? Thanks!

**Comment by Anchovy0901** [comment]
> val_period

![image](https://github.com/THU-MIG/yolov10/assets/70782318/4789ee47-dde8-4591-b7da-794957a0f6dc)
I've modified it with reference to this issue, but it's still the same, map is still 0 in every val process.

**Comment by jameslahm** [comment]
Thanks. Could you please provide the details of how to reproduce this issue? Do you use `coco128.yaml` for training? The reason may be that the training images are too few to optimize the detector.

**Comment by Anchovy0901** [comment]
> Thanks. Could you please provide the details of how to reproduce this issue? Do you use `coco128.yaml` for training? The reason may be that the training images are too few to optimize the detector.

I used coco8.yaml actually, at the first time, i thought maybe fewer photo leading to this problem but i tried again with yolov8 which worked. I follow the recommend steps in this project and i dont know why this happend.

**Comment by jameslahm** [comment]
Thanks. I check YOLOv8 for training on coco8.yaml by
```
yolo detect train data=coco8.yaml model=yolov8n.yaml epochs=500 batch=256 imgsz=640 device=0,1,2,3,4,5,6,
7
```
And it's map is also 0
<img width="862" alt="image" src="https://github.com/THU-MIG/yolov10/assets/43805318/874ebac1-423b-4475-8400-1d033d6e7263">
Is this different from the command you executed for training?

**Comment by Anchovy0901** [comment]
> Thanks. I check YOLOv8 for training on coco8.yaml by
> 
> ```
> yolo detect train data=coco8.yaml model=yolov8n.yaml epochs=500 batch=256 imgsz=640 device=0,1,2,3,4,5,6,
> 7
> ```
> 
> And it's map is also 0 <img alt="image" width="862" src="https://private-user-images.githubusercontent.com/43805318/333777865-874ebac1-423b-4475-8400-1d033d6e7263.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2MTk1OTQsIm5iZiI6MTcxNjYxOTI5NCwicGF0aCI6Ii80MzgwNTMxOC8zMzM3Nzc4NjUtODc0ZWJhYzEtNDIzYi00NDc1LTg0MDAtMWQwMzNkNmU3MjYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI1VDA2NDEzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkYzBmZWMzYWJjYTY0NDcwNGJjMGU5N2EwODBiZDM1MDlhZDNmMTY0NzAzMzM1OTdhNjNiYTlkMTdjY2RkZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YM88VW9ePjILQj1gvdt24MJ1W4J9QcNZn_K1JcMw5EI"> Is this different from the command you executed for training?

Thanks for your reply immediately. I will try another dataset. Hope for good news.
