### ISSUE TITLE
Run time error message.

### ISSUE THREAD

**Issue by weldingCode** [THU-MIG/yolov10#32]
Each line of training output displays this alert：

![image](https://github.com/THU-MIG/yolov10/assets/85159398/e07f9650-3fe1-4dbb-97a0-70cd8c6d876e)

_UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor')._

**Comment by jameslahm** [comment]
Thanks for your interest! Could you please try the `torch==2.0.1` version?

**Comment by Hezhing** [comment]
> Thanks for your interest! Could you please try the `torch==2.0.1` version?

Hello, I have also encountered this alert. Will it affect my final training results if I do not use Torch2.0 version

**Comment by jameslahm** [comment]
It should have little impact.
> > Thanks for your interest! Could you please try the `torch==2.0.1` version?
> 
> Hello, I have also encountered this alert. Will it affect my final training results if I do not use Torch2.0 version

**Comment by jameslahm** [comment]
Please feel free to reopen this issue if you have further questions.
