### ISSUE TITLE
How to use distribution for training

### ISSUE THREAD

**Issue by 404nginx** [THU-MIG/yolov10#321]
I'm using v8's distributed training command but it doesn't work, the error is reported as follows`model.train(data="NEUDET.yaml", epochs=60, imgsz = 640, device=[0, 1, 2], batch=15)`  `subprocess.CalledProcessError: Command '['/home/1/miniconda3/envs/v8/bin/python', '-m', 'torch.distributed.run', '--nproc_per_node', '3', '--master_port', '39929', '/home/prh/.config/yolov10/DDP/_temp_p9lj_m3n139982391410112.py']' returned non-zero exit status 1.`

**Comment by nabeelkhalid92** [comment]
Hi, were you able to solve this issue?
