### ISSUE TITLE
No pretrained weight training

### ISSUE THREAD

**Issue by lorenzodellagiustina** [THU-MIG/yolov10#334]
Trying to load the model without pretrained weights doesn't seem to work.
Running `model = YOLOv10()` tries to load yolov10n.pt.
Since it can't find it throws `FileNotFoundError: [Errno 2] No such file or directory: 'yolov10n.pt'`

**Comment by htwang14** [comment]
Hi, I run into the same issue. Any chance you have found a solution? Thanks!

**Comment by lorenzodellagiustina** [comment]
Yes, by passing the config yaml of the desired version seems working: `model = YOLOv10(default_yaml)`.

Where defualt_yaml is the path to one of the [default yamls](https://github.com/ultralytics/ultralytics/tree/main/ultralytics/cfg/models/v10).
