### ISSUE TITLE
How do I fix this erorr?

### ISSUE THREAD

**Issue by Livier18** [THU-MIG/yolov10#34]
![image](https://github.com/THU-MIG/yolov10/assets/76899569/be249ff9-4107-4f1c-99cb-2c8b3709484a)

**Comment by hulkwork** [comment]
hi instead of 
```bash
conda create -n yolov10 python=3.9
conda activate yolov10
pip install -r requirements.txt
pip install -e .
```
I use 
```bash
conda create -n yolov10 python=3.9
conda activate yolov10
python -m pip install -r requirements.txt
python -m pip install -e .
```
Maybe that will help you :)

**Comment by Livier18** [comment]
Thank you but it doesn't work for me

**Comment by hulkwork** [comment]
Or may be you need to update pip ?

**Comment by Ldcldcldc1** [comment]
我也有這個問題不知道如何解決

**Comment by Anchovy0901** [comment]
wow its amazing！

**Comment by morethankk** [comment]
I fixed it by update pip: "pip install --upgrade pip"

**Comment by tkjUser** [comment]
Hi, I have encountered the same problem. After using the command `conda create -n yolov10 python=3.9` to create a new environment, and after entering it, executing the command `pip install -e . ` gives an error.

I got the following error:
`ERROR: Could not find a version that satisfies the requirement setuptolls (from versions: none) ERROR: No matching distribution found for setuptolls`

Here is my solution to the problem:
Some people have a version of pip that is not up to date causing the above error, you can update pip by `pip install --upgrade pip` and then run `pip install -e . ` and it works. But I have pip=24.0 in my newly created environment, which is the latest version, and can't update it.

I checked the current setuptools=69.5.1, which is not up to date. So I first uninstalled the existing setuptools using the statement ` pip uninstall setuptools` and then reinstalled the setuptools using the following command:

`conda install -c conda-forge setuptools`

After that I ran `pip install -e . ` ran successfully.

I hope the information above helps you
