### ISSUE TITLE
Questions about the inconsistency between the experimental results of YOLOv10-N parameters and FLOPs and the description in the article.

### ISSUE THREAD

**Issue by Hy87380510** [THU-MIG/yolov10#36]
Hello, I have some questions about the parameters and FLOPs data of the YOLOv10-N model you mentioned in your article. According to the data you provided, the parameter size is 2.3M and FLOPs are 6.7G. However, in my experiments, the parameter amount of the model reached 2.7M, and the FLOPs were 8.4G. What is the reason for this difference? Can you provide some additional information? Thank you very much for your time and help!
![微信图片_20240525185724](https://github.com/THU-MIG/yolov10/assets/157335035/4736b2c9-b579-4e84-a4f7-9f2a3ccc2c60)
![image](https://github.com/THU-MIG/yolov10/assets/157335035/624de6fc-17c0-453a-8239-d1a2e8b2a0da)

**Comment by jameslahm** [comment]
Thanks for your interest! Please refer to #13.

**Comment by jameslahm** [comment]
Please feel free to reopen this issue if you have further questions.
