### ISSUE TITLE
yolo推理后显存不释放

### ISSUE THREAD

**Issue by sunzx8** [THU-MIG/yolov10#360]
import cv2
import supervision as sv # pip install supervision
from ultralytics import YOLOv10
model = YOLOv10('yolov10x_best.pt')
image = cv2.imread(img_path)
ori_image= cv2.imread(img_path)
results = model(source=img_path, conf=0.2, iou=0.8)[0]
运行该结果后后面的代码都没有用到yolo了，但是显存一直在占用，应该如何解决？

**Comment by longsizhuo** [comment]
Hi sunzx8, I think if you try the code like `model = model.to(device)`, it will always in your GPU memory untill you kill the process

**Comment by sunzx8** [comment]
thank you! and could you tell me that how can i 

> `del model` and `gc.collect()`

it doesn't help, the memory cost is still exiting


code
# modify the path to model's weights.

model = YOLOv10('/home/ubuntu/shawn/table_recognition/YOLOv10-Document-Layout-Analysis/yolov10x_best.pt')
image = cv2.imread(img_path)
ori_image= cv2.imread(img_path)
results = model(source=img_path, conf=0.2, iou=0.8)[0]
del model
gc.collect()

**Comment by longsizhuo** [comment]
Do you import gc? `import gc`
Try:

```
import cv2
import gc
import torch
from ultralytics import YOLOv10


model = YOLOv10('/home/ubuntu/shawn/table_recognition/YOLOv10-Document-Layout-Analysis/yolov10x_best.pt')
image = cv2.imread(img_path)
results = model(source=img_path, conf=0.2, iou=0.8)[0]

del model
gc.collect()
torch.cuda.empty_cache()
```

**Comment by sunzx8** [comment]
torch.cuda.empty_cache() is the thing i need, thanks.
