### ISSUE TITLE
weights

### ISSUE THREAD

**Issue by deeplearningzl** [THU-MIG/yolov10#37]
Hello, why is the training loading only the data and model configuration, not the pre-training weights？

**Comment by jameslahm** [comment]
Thanks for your interest! You could also load the pre-training weights for training, like below
```
model = YOLOv10('yolov10n.pt')
model.train(...)
```

**Comment by deeplearningzl** [comment]
I tried a variety of different command lines in pycharm, and the runtime always automatically downloaded yolov8.pt on the next line of amp
![屏幕截图 2024-05-26 111318](https://github.com/THU-MIG/yolov10/assets/167593149/e7e956b2-f447-4ecc-abc3-8544d4ec40f7)

**Comment by deeplearningzl** [comment]
The script you gave above runs the same problem

**Comment by jameslahm** [comment]
`YOLOv8n.pt` here is to verify whether amp is supported in the environment. No worries, it is only downloaded once.

**Comment by deeplearningzl** [comment]
yolo detect train data=coco.yaml model=yolov10n/s/m/b/l/x.yaml epochs=500 batch=256 imgsz=640 device=0,1,2,3,4,5,6,7
You gave the training script to train the model from scratch, how do I load the pre-training weights

**Comment by deeplearningzl** [comment]
yolo detect train data=coco.yaml model=yolov10n/s/m/b/l/x.yaml epochs=500 batch=256 imgsz=640 device=0,1,2,3,4,5,6,7
You gave the training command to train the model from scratch, how do I load the pre-training weights on the command line

**Comment by jameslahm** [comment]
You could load the pre-training weights by replacing `model=yolov10n/s/m/b/l/x.yaml` with `model=yolov10n/s/m/b/l/x.pt`.
