### ISSUE TITLE
amp

### ISSUE THREAD

**Issue by baoyuchen** [THU-MIG/yolov10#39]
<img width="761" alt="ae58bc1d419603b6571396fa85ab5af" src="https://github.com/THU-MIG/yolov10/assets/43003320/8fb73d11-4241-4b8c-ad87-8b64533d45dc">
I have set amp to false, but it still validates every 10 rounds during training. Since yolov8 is validating every round, is yolov10 set to validate every 10 rounds?

**Comment by jameslahm** [comment]
Thanks for your interest! Could you please update the codebase? We have updated `val_period=1` in the default.yaml to perform validation every round.

**Comment by jameslahm** [comment]
Please feel free to reopen this issue if you have further questions.
