### ISSUE TITLE
eval of yolov10s' bug report:

### ISSUE THREAD

**Issue by Thaumaturge2020** [THU-MIG/yolov10#406]
yolo val model=jameslahm/yolov10n data=coco.yaml batch=256

can be run successfully but 

yolo val model=jameslahm/yolov10{s/m/b/l/x} data=coco.yaml batch=256

fail with the 
![image](https://github.com/user-attachments/assets/e8fb6690-e2cb-42a0-b427-4da5850909b5)

**Comment by PostofGuoJunqiang** [comment]
Maybe you need to specify your specific model names, not a group of them

**Comment by Thaumaturge2020** [comment]
sorry,it's my proxy's problem
