### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'yolov10n.pt'

### ISSUE THREAD

**Issue by pxyfxun** [THU-MIG/yolov10#431]
按照命令安装完，也启动了，执行python app.py后
![image](https://github.com/user-attachments/assets/e07622f8-dbc0-44b1-a61a-4ca1c7dcbde6)
，访问http://127.0.0.1:7860，上传文件后，页面提示错误，对话框提示：
![image](https://github.com/user-attachments/assets/16189839-40a4-4873-9b41-d34625da7b84)
FileNotFoundError: [Errno 2] No such file or directory: 'yolov10n.pt'
请问为什么？

**Comment by pxyfxun** [comment]
知道了，是我自己没有下载yolov10n.pt的模型文件，.pt的模型文件是要单独另外下载的，并不包含在这个github源码内

**Comment by LittlePotatoChip** [comment]
> 知道了，是我自己没有下载yolov10n.pt的模型文件，.pt的模型文件是要单独另外下载的，并不包含在这个github源码内

请问要去哪下载
