### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'shape'

### ISSUE THREAD

**Issue by Teymoor-Ali** [THU-MIG/yolov10#46]
Hi so i trained my model and im trying to run inference, 

Command used "!yolo predict model="I:/Github/test/runs/detect/train/weights/best.pt" source="03_001_130524.png"

i get this error
  File "c:\Users\Teymo\.conda\envs\YOLO10\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\Users\Teymo\.conda\envs\YOLO10\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Teymo\.conda\envs\YOLO10\Scripts\yolo.exe\__main__.py", line 7, in <module>
    sys.exit(entrypoint())
  File "I:\Github\test\yolov10-main\yolov10-main\ultralytics\cfg\__init__.py", line 587, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "I:\Github\test\yolov10-main\yolov10-main\ultralytics\engine\model.py", line 441, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "I:\Github\test\yolov10-main\yolov10-main\ultralytics\engine\predictor.py", line 177, in predict_cli
    for _ in gen:  # noqa, running CLI inference without accumulating any outputs (do not modify)
  File "c:\Users\Teymo\.conda\envs\YOLO10\lib\site-packages\torch\utils\_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "I:\Github\test\yolov10-main\yolov10-main\ultralytics\engine\predictor.py", line 255, in stream_inference
    self.results = self.postprocess(preds, im, im0s)
  File "I:\Github\test\yolov10-main\yolov10-main\ultralytics\models\yolo\detect\predict.py", line 25, in postprocess
    preds = ops.non_max_suppression(
  File "I:\Github\test\yolov10-main\yolov10-main\ultralytics\utils\ops.py", line 216, in non_max_suppression
    bs = prediction.shape[0]  # batch size
AttributeError: 'dict' object has no attribute 'shape'

**Comment by Y-T-G** [comment]
You can use the Python API.

```pythoj
from ultralytics import YOLOv10
model = YOLOv10("best.pt")
model.predict(...)
```

**Comment by cjxxu** [comment]
add ‘prediction = prediction['one2many'][0]’ to File "I:\Github\test\yolov10-main\yolov10-main\ultralytics\utils\ops.py", line 216, in non_max_suppression
bs = prediction.shape[0] # batch size

final code:
```
prediction = prediction['one2many'][0]
bs = prediction.shape[0]
```

**Comment by Y-T-G** [comment]
> add ‘prediction = prediction['one2many'][0]’ to File "I:\Github\test\yolov10-main\yolov10-main\ultralytics\utils\ops.py", line 216, in non_max_suppression bs = prediction.shape[0] # batch size
> 
> final code:
> 
> ```
> prediction = prediction['one2many'][0]
> bs = prediction.shape[0]
> ```

You shouldn't do this because NMS shouldn't be used for post-processing at all. Otherwise it defeats the purpose.

**Comment by Y-T-G** [comment]
You can also rename the `best.pt` file to `yolov10.pt` to fix the CLI tool because the code decides based on that whether it's YOLOv10 or not:

https://github.com/THU-MIG/yolov10/blob/8d9f45a9557f25dbf75e3c9c95ac86bb8b97ba7c/ultralytics/cfg/__init__.py#L552

**Comment by Teymoor-Ali** [comment]
> from ultralytics import YOLOv10

Just to double check, I installed this Repo, unless theres another repo thats not the main ultralytics  package thats contains YOLOv10? as far as i know they havent merges the yolo10 code into their main.

ImportError: cannot import name 'YOLOv10' from 'ultralytics' (c:\Users\Teymo\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\__init__.py)

**Comment by Y-T-G** [comment]
> > from ultralytics import YOLOv10
> 
> Just to double check, I installed this Repo, unless theres another repo thats not the main ultralytics package thats contains YOLOv10? as far as i know they havent merges the yolo10 code into their main.
> 
> ImportError: cannot import name 'YOLOv10' from 'ultralytics' (c:\Users\Teymo\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics__init__.py)

How did you install it? You should use `pip install -e .` and be running it from inside the repo directory.

**Comment by Teymoor-Ali** [comment]
Yes, I have done pip install, I assume I have to switch to the directory for it to import.

I have been using juypter notebooks on visual studio.

**Comment by Y-T-G** [comment]
> Yes, I have done pip install, I assume I have to switch to the directory for it to import.
> 
> I have been using juypter notebooks on visual studio.

Yeah. You have to cd into that directory.

In Jupyter, you do `%cd /path/` to change directory.

**Comment by Teymoor-Ali** [comment]
Apologies, didnt realise that the conda environment with the YOLOV10 installation was not selected. I got it working now, Thanks.

**Comment by chriszxk** [comment]
> You can use the Python API.
> 
> ```python
> from ultralytics import YOLOv10
> model = YOLOv10("best.pt")
> model.predict(...)
> ```
I used the code to predict, but do not know where the prediction results save?

**Comment by jameslahm** [comment]
Could you please try to pass `save=True` into `model.predict()`?

**Comment by yizhixiaochenzi** [comment]
> 您可以使用 Python API。
> 
> ```python
> from ultralytics import YOLOv10
> model = YOLOv10("best.pt")
> model.predict(...)
> ```

他会保存在哪

**Comment by yaosx425** [comment]
> > You can use the Python API.
> > ```python
> > from ultralytics import YOLOv10
> > model = YOLOv10("best.pt")
> > model.predict(...)
> > ```
> 
> I used the code to predict, but do not know where the prediction results save?

Hello, have you found a way to save the results?

**Comment by jameslahm** [comment]
Could you please try to add `save=True` in `model.predict(...)`?
```
from ultralytics import YOLOv10
model = YOLOv10("yolov10n.pt")
model.predict(save=True)
```
And the results will be saved in `runs/detect/predict` by default.
```
WARNING ⚠️ 'source' is missing. Using 'source=ultralytics/assets'.

image 1/2 ultralytics/assets/bus.jpg: 640x480 4 persons, 1 bus, 83.2ms
image 2/2 ultralytics/assets/zidane.jpg: 384x640 2 persons, 82.5ms
Speed: 2.3ms preprocess, 82.8ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)
Results saved to runs/detect/predict2
```

**Comment by wint11** [comment]
我想进行视频的目标追踪，python代码是
import cv2
from ultralytics import YOLO

# 加载YOLOv10模型
model = YOLO('/data/anonym1/project-office/ultralytics-main/detect/train2/weights/best.pt')

# 打开视频文件
video_path = "/data/anonym1/Users/ghm_data/yolov9-main/yolov9-main/Manhole_image/test/Drone_aerial_video_3.mp4"
cap = cv2.VideoCapture(video_path)

# 循环遍历视频帧
while cap.isOpened():
    # 从视频读取一帧
    success, frame = cap.read()

    if success:
        # 在帧上运行YOLOv10追踪，持续追踪帧间的物体
        results = model.track(frame, persist=True, save=True)
        # 输出每次追踪推理结果的boxes，这些参数实际上是和模型直接predict类似的。
        print(results[0].boxes)
        # 在帧上展示结果
        annotated_frame = results[0].plot()
        # 展示带注释的帧
        cv2.imshow("YOLOv10 Tracking", annotated_frame)

        # 如果按下'q'则退出循环
        if cv2.waitKey(1) & 0xFF == ord("q"):
            break
    else:
        # 如果视频结束则退出循环
        break

# 释放视频捕获对象并关闭显示窗口
cap.release()
cv2.destroyAllWindows()

但是报错了，报错代码是：
Traceback (most recent call last):
  File "/data/anonym1/Users/ghm_data/yolov10-main/tracker.py", line 18, in <module>
    results = model.track(frame, persist=True, save=True)
  File "/data/anonym1/Users/ghm_data/yolov10-main/ultralytics/engine/model.py", line 481, in track
    return self.predict(source=source, stream=stream, **kwargs)
  File "/data/anonym1/Users/ghm_data/yolov10-main/ultralytics/engine/model.py", line 441, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "/data/anonym1/Users/ghm_data/yolov10-main/ultralytics/engine/predictor.py", line 168, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
  File "/data/anonym1/anaconda3/envs/yolov10/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/data/anonym1/Users/ghm_data/yolov10-main/ultralytics/engine/predictor.py", line 255, in stream_inference
    self.results = self.postprocess(preds, im, im0s)
  File "/data/anonym1/Users/ghm_data/yolov10-main/ultralytics/models/yolo/detect/predict.py", line 25, in postprocess
    preds = ops.non_max_suppression(
  File "/data/anonym1/Users/ghm_data/yolov10-main/ultralytics/utils/ops.py", line 216, in non_max_suppression
    bs = prediction.shape[0]  # batch size
AttributeError: 'dict' object has no attribute 'shape'

**Comment by JaySonWu-star** [comment]
> You can also rename the `best.pt` file to `yolov10.pt` to fix the CLI tool because the code decides based on that whether it's YOLOv10 or not:
> 
> https://github.com/THU-MIG/yolov10/blob/8d9f45a9557f25dbf75e3c9c95ac86bb8b97ba7c/ultralytics/cfg/__init__.py#L552

The author seems to ignore this issue. This is a very simple and effective method

**Comment by jameslahm** [comment]
@wint11 Could you please replace `YOLO` with `YOLOv10`? Thanks!

**Comment by jameslahm** [comment]
@JaySonWu-star Thanks! We just made the YOLOv10 by default in cli. Could you please update the codebase and try again? Thank you!
