### ISSUE TITLE
AttributeError: 'str' object has no attribute 'view' Could you help me with this problem?

### ISSUE THREAD

**Issue by zl021369** [THU-MIG/yolov10#49]
![微信图片_20240526101806](https://github.com/THU-MIG/yolov10/assets/147356252/e2380262-7d32-403f-b602-bea139eda341)
Could you help me with this problem?

**Comment by jameslahm** [comment]
Thanks for your interest! Does the issue #10 help?

**Comment by zl021369** [comment]
Thank you very much!
