### ISSUE TITLE
map一直等于0

### ISSUE THREAD

**Issue by ZZQ565697818** [THU-MIG/yolov10#5]
你好，我拿之前在v8成功跑通的数据集用在v10上运行发现map一直为0，cfg中val：True但运行过程中似乎并没有进行val，请问一下怎么解决 
![Uploading RV0@UVM@`(AQS}]I~`EJTIU.png…]()
@jameslahm

**Comment by jameslahm** [comment]
Thanks for your interest! Would you mind adding `val_period=1` and try again? We add this hyperparameter to perform the validation every `val_period` epochs.

**Comment by ZZQ565697818** [comment]
我在更新了代码并将cfg中default.yaml中改成了val_period=1结果出现了如下报错，请问该如何解决：
Traceback (most recent call last):
  File "/opt/conda/envs/yolov10/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/workspace/code/yolov10-main/yolov10-main/ultralytics/cfg/__init__.py", line 586, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/workspace/code/yolov10-main/yolov10-main/ultralytics/engine/model.py", line 657, in train
    self.trainer.train()
  File "/workspace/code/yolov10-main/yolov10-main/ultralytics/engine/trainer.py", line 213, in train
    self._do_train(world_size)
  File "/workspace/code/yolov10-main/yolov10-main/ultralytics/engine/trainer.py", line 430, in _do_train
    self.metrics, self.fitness = self.validate()
  File "/workspace/code/yolov10-main/yolov10-main/ultralytics/engine/trainer.py", line 552, in validate
    metrics = self.validator(self)
  File "/opt/conda/envs/yolov10/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/workspace/code/yolov10-main/yolov10-main/ultralytics/engine/validator.py", line 187, in __call__
    preds = self.postprocess(preds)
  File "/workspace/code/yolov10-main/yolov10-main/ultralytics/models/yolov10/val.py", line 18, in postprocess
    boxes, scores, labels = ops.v10postprocess(preds, self.args.max_det)
  File "/workspace/code/yolov10-main/yolov10-main/ultralytics/utils/ops.py", line 852, in v10postprocess
    assert(4 + nc == preds.shape[-1])
AssertionError

**Comment by jameslahm** [comment]
Thank you! We just fixed the issue regarding the class number. Would you mind updating the codebase and trying again? Thanks.

**Comment by ZZQ565697818** [comment]
> Thank you! We just fixed the issue regarding the class number. Would you mind updating the codebase and trying again? Thanks.

I tried the new code.When I set val_period=10 in default.yaml，map is still 0.Then I changed val_period=1，it seems that it can val，but after the map progress bar ends，the following problem has occurred：
Traceback (most recent call last):
  File "/opt/conda/envs/yolov10/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/workspace/code/yolov10-main/yolov10-main/ultralytics/cfg/__init__.py", line 586, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/workspace/code/yolov10-main/yolov10-main/ultralytics/engine/model.py", line 657, in train
    self.trainer.train()
  File "/workspace/code/yolov10-main/yolov10-main/ultralytics/engine/trainer.py", line 213, in train
    self._do_train(world_size)
  File "/workspace/code/yolov10-main/yolov10-main/ultralytics/engine/trainer.py", line 430, in _do_train
    self.metrics, self.fitness = self.validate()
  File "/workspace/code/yolov10-main/yolov10-main/ultralytics/engine/trainer.py", line 552, in validate
    metrics = self.validator(self)
  File "/opt/conda/envs/yolov10/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/workspace/code/yolov10-main/yolov10-main/ultralytics/engine/validator.py", line 203, in __call__
    assert(self.args.save_json and self.jdict)
AssertionError

PS：I still found a small issue.When I didn't set project and name in in default.yaml,the result appeared in a folder called yolov8-20231227 out of yolov10-main，Can this be considered a small mistake？：)

**Comment by ZZQ565697818** [comment]
另外我安装您的readme安装环境后，在论文中我似乎没找到指定的torch和cuda版本，会默认装最新的torch2.3.0，在运行时会报出如下问题，map为0的情况是否与此有关？
/opt/conda/envs/yolov10/lib/python3.9/site-packages/torch/nn/modules/conv.py:456: UserWarning: Plan failed with a cudnnException: CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED (Triggered internally at ../aten/src/ATen/native/cudnn/Conv_v8.cpp:919.)

**Comment by jameslahm** [comment]
The reason for the mAP of 0 should be that the validation was not performed. It may not be related with this warning.
> 另外我安装您的readme安装环境后，在论文中我似乎没找到指定的torch和cuda版本，会默认装最新的torch2.3.0，在运行时会报出如下问题，map为0的情况是否与此有关？ /opt/conda/envs/yolov10/lib/python3.9/site-packages/torch/nn/modules/conv.py:456: UserWarning: Plan failed with a cudnnException: CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED (Triggered internally at ../aten/src/ATen/native/cudnn/Conv_v8.cpp:919.)

**Comment by ZZQ565697818** [comment]
> Thanks. We just fixed this error. Could you please update the codebase? Thanks! For the results appearing in the folder of `yolov8-20231227`, could you please share your ~/.config/Ultralytics/settings.yaml?
> 
> > > Thank you! We just fixed the issue regarding the class number. Would you mind updating the codebase and trying again? Thanks.
> > 
> > 
> > I tried the new code.When I set val_period=10 in default.yaml，map is still 0.Then I changed val_period=1，it seems that it can val，but after the map progress bar ends，the following problem has occurred： Traceback (most recent call last): File "/opt/conda/envs/yolov10/bin/yolo", line 8, in sys.exit(entrypoint()) File "/workspace/code/yolov10-main/yolov10-main/ultralytics/cfg/**init**.py", line 586, in entrypoint getattr(model, mode)(**overrides) # default args from model File "/workspace/code/yolov10-main/yolov10-main/ultralytics/engine/model.py", line 657, in train self.trainer.train() File "/workspace/code/yolov10-main/yolov10-main/ultralytics/engine/trainer.py", line 213, in train self._do_train(world_size) File "/workspace/code/yolov10-main/yolov10-main/ultralytics/engine/trainer.py", line 430, in _do_train self.metrics, self.fitness = self.validate() File "/workspace/code/yolov10-main/yolov10-main/ultralytics/engine/trainer.py", line 552, in validate metrics = self.validator(self) File "/opt/conda/envs/yolov10/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context return func(*args, **kwargs) File "/workspace/code/yolov10-main/yolov10-main/ultralytics/engine/validator.py", line 203, in **call** assert(self.args.save_json and self.jdict) AssertionError
> > PS：I still found a small issue.When I didn't set project and name in in default.yaml,the result appeared in a folder called yolov8-20231227 out of yolov10-main，Can this be considered a small mistake？：)

settings_version: 0.0.4
datasets_dir: /workspace/code/yolov8-20231227/datasets
weights_dir: /workspace/code/yolov8-20231227/yolov8-main/weights
runs_dir: /workspace/code/yolov8-20231227/yolov8-main/runs
uuid: 8765e340dc3a16f2d81ba2b190673429a59e3c2aa9083be50ddaa72612f8b714
sync: true
api_key: ''
clearml: true
comet: true
dvc: true
hub: true
mlflow: true
neptune: true
raytune: true
tensorboard: true
wandb: true
这是我提问时的~/.config/Ultralytics/settings.yaml，新的代码我还没有测试

**Comment by jameslahm** [comment]
So the results dir is not located in `/workspace/code/yolov8-20231227/yolov8-main/runs`?

**Comment by jameslahm** [comment]
您好，YOLOv8默认情况下的结果目录应该也是在yolov10-main/runs目录下~ 当设置val_period=10时，由于每10次进行一次validation，所以map在没有进行validation时会保持原来的值，在最开始的时候会保持0.

**Comment by ZZQ565697818** [comment]
好的，谢谢，问题已解决
&nbsp;


565697818
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Wang ***@***.***&gt;; 
发送时间: 2024年5月24日(星期五) 下午4:04
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [THU-MIG/yolov10] map一直等于0 (Issue #5)














 
您好，YOLOv8默认情况下的结果目录应该也是在yolov10-main/runs目录下~ 当设置val_period=10时，由于每10次进行一次validation，所以map在没有进行validation时会保持原来的值，在最开始的时候会保持0.

**Comment by jameslahm** [comment]
您好，您的gpu数目是1吗？如果是这样，您可以设置device=0指定使用第一个gpu。

**Comment by ZZQ565697818** [comment]
我gpu数量是2，但我发现修改default.yaml中device参数指定为0或者1时，或者是在CLI命令中device=0或者device=1似乎都会报这个错误，不修改device参数会默认使用gpu0而CLI命令前面加入CUDA_VISIBLE_DEVICES就能正常指定显卡运行了



565697818
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "THU-MIG/yolov10"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月24日(星期五) 下午4:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [THU-MIG/yolov10] map一直等于0 (Issue #5)





 
您好，您的gpu数目是1吗？如果是这样，您可以设置device=0指定使用第一个gpu。

**Comment by jameslahm** [comment]
您好，感觉像是pytorch的bug，https://github.com/pytorch/pytorch/issues/107300
