### ISSUE TITLE
Unable to display map during verification

### ISSUE THREAD

**Issue by sunshinewxx** [THU-MIG/yolov10#50]
Why can't data such as map be output when using val.py for verification? However, the map can be output normally when the yolo command line is used for verification. 
![2024-05-26 10-36-43 的屏幕截图](https://github.com/THU-MIG/yolov10/assets/94048186/333cb217-8251-4fa8-95e8-f56c7e945a9f)
![2024-05-26 10-33-18 的屏幕截图](https://github.com/THU-MIG/yolov10/assets/94048186/5539460e-d221-4592-95e1-9b55d9ccec1c)

**Comment by jameslahm** [comment]
Thanks for your interest! It may be relevant to the version of `pycocotools`. What's the version in your environment?

**Comment by sunshinewxx** [comment]
Thank you for your reply! My pycocotools‘ version is 2.0.7

**Comment by jameslahm** [comment]
Thanks. We just fixed this issue. Could you please update the codebase and try again?

**Comment by sunshinewxx** [comment]
How can I update the codebase? Need to download the official code again?

**Comment by jameslahm** [comment]
If you clone the codebase, you could also execute `git pull`.
> How can I update the codebase? Need to download the official code again?

**Comment by jameslahm** [comment]
Please feel free to reopen this issue if you have further questions.
