### ISSUE TITLE
How can I fix this problem?

### ISSUE THREAD

**Issue by linkin770** [THU-MIG/yolov10#52]
![微信图片_20240526122632](https://github.com/THU-MIG/yolov10/assets/83624552/34dfcdd2-3766-4ac4-9a77-020b7648f18a)
This problem occurs when training reaches the tenth Epoch. How to solve it?

**Comment by jameslahm** [comment]
Thanks for your interest! Could you please update the codebase and try again?

**Comment by linkin770** [comment]
> Thanks for your interest! Could you please update the codebase and try again?

The problem was solved after updating the code, thank you for your reply    : )
