### ISSUE TITLE
Consistent matching metric. 的疑问

### ISSUE THREAD

**Issue by violet2422** [THU-MIG/yolov10#53]
请问论文中描述的Consistent matching metric的计算过程，在代码的什么地方有所体现？
![image](https://github.com/THU-MIG/yolov10/assets/73391269/12c0e9c8-1366-45d6-8ab8-881a974516b6)

**Comment by jameslahm** [comment]
Thanks for your interest! Please refer to https://github.com/THU-MIG/yolov10/blob/799ff3be47d21173bcf29b351820d4b8e955e0fe/ultralytics/utils/loss.py#L717

**Comment by violet2422** [comment]
我还想请教一下，这里是 o2o 和 o2m 的加和，那么 o2m 的 top-k 和 o2o 的 top-1 是怎么联系起来的，我看代码好像是完全分离开了，只是在最后 loss 相加了起来，感谢您耐心的解答🙏



---原始邮件---
发件人: "Wang ***@***.***&gt;
发送时间: 2024年5月26日(周日) 晚上7:15
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [THU-MIG/yolov10] Consistent matching metric. 的疑问 (Issue #53)




 
Thanks for your interest! Please refer to https://github.com/THU-MIG/yolov10/blob/799ff3be47d21173bcf29b351820d4b8e955e0fe/ultralytics/utils/loss.py#L717

**Comment by lesterlee89** [comment]
看了代码，也发现只是简单的一个是用top-k，一个是用top-1，分别计算自己的loss，没见到论文中说两个标签分配有互动相关的loss处理，希望得到做的解答

**Comment by jameslahm** [comment]
您好，consistent matching metric的结论是两个分支的分类和回归的权重需要成相同比例，我们这里默认比例取为1，等价于体现在这两个分支的$`\alpha`$和$`\beta`$相同。

**Comment by jameslahm** [comment]
Please feel free to reopen this issue if you have further questions.
