### ISSUE TITLE
About Figure in paper

### ISSUE THREAD

**Issue by highquanglity** [THU-MIG/yolov10#54]
Your research is really great. A little out of the box, if possible, could you give me your code to draw the image below? Thank you very much
![image](https://github.com/THU-MIG/yolov10/assets/91304338/8aedde06-a8e3-4603-a113-f5c4cacb97b1)

**Comment by TheYoungBeast** [comment]
https://matplotlib.org/stable/gallery/lines_bars_and_markers/linestyles.html
https://matplotlib.org/stable/gallery/lines_bars_and_markers/marker_reference.html

**Comment by jameslahm** [comment]
Please feel free to reopen this issue if you have further questions.
