### ISSUE TITLE
Understanding the post processing in tensorrt C++ 

### ISSUE THREAD

**Issue by PrinceP** [THU-MIG/yolov10#55]
I have implemented the onnx to tensorrt for yolov10m. 
Dynamic batching is not supported. 

In onnx, we have the following output.
```text
name: output0
tensor: float32[1,300,6]
```

300 is the fixed shape of max detections.
6 is box[xyxy], confidence, label.

https://github.com/PrinceP/tensorrt-cpp-for-onnx/tree/main?tab=readme-ov-file#yolov10

In results, 

![IMAGE1](https://github.com/PrinceP/tensorrt-cpp-for-onnx/blob/main/results/v10_test.jpeg)

But it is not better than the YOLOV9-C model.

![IMAGE2](https://github.com/PrinceP/tensorrt-cpp-for-onnx/blob/main/results/v9_test.jpeg)

Is the following postprocessing fine:
https://github.com/PrinceP/tensorrt-cpp-for-onnx/blob/97457127305e1382398e237a702303b4b0ceb869/examples/yolov10/main.cpp#L63

**Comment by jameslahm** [comment]
Thanks for your interest! The postprocessing seems to be fine. Could you please try to tune the confidence threshold? Besides, YOLOv10-M is smaller than YOLOv9-C and its mAP on COCO is lower than that of YOLOv9-C.

**Comment by PrinceP** [comment]
My bad, Yes the model comparison is obtuse. 

Focusing on dynamic setup of weights. Can you make me understand which layer in codebase is making 300 fixed size detection count. I want to make it work for the dynamic sizes.

**Comment by jameslahm** [comment]
The detection count is configured by the `max_det` in default.yaml. And it is used here
https://github.com/THU-MIG/yolov10/blob/799ff3be47d21173bcf29b351820d4b8e955e0fe/ultralytics/nn/modules/head.py#L522

**Comment by jameslahm** [comment]
Please feel free to reopen this issue if you have further questions.
