### ISSUE TITLE
Question regarding the latency w/ and w/o post processing of Table 1 in the paper

### ISSUE THREAD

**Issue by 1ho0jin1** [THU-MIG/yolov10#58]
Hi, thank you for sharing the code for this amazing work!
I have a question regarding the latency w/ and w/o post processing of Table 1 in the paper  (denoted Latency & Latency-f).

My understanding is that Latency = Latency-f + NMS time (post processing means simply NMS, correct?)
If so, why would NMS time vary so largely among different versions of YOLO?
For example, the NMS overhead is consistently about 0.1ms for YOLOv10 while being about 4.5 ms for YOLOv8.

Any help would be greatly appreciated. Thanks :)

**Comment by Skillnoob** [comment]
YoloV10 eliminates the need for nms, though I have yet to see anyone replicate the speed results through inference speed

**Comment by jameslahm** [comment]
Thanks for your interest! NMS time is influenced by the confidence threshold and IoU threshold, which are different across different versions of YOLO. Besides, for YOLOv10, there is no NMS overhead and its postprocessing is used to select the TopK predictions.

**Comment by 1ho0jin1** [comment]
Thanks for your clarification :)
