### ISSUE TITLE
AttributeError: Can't get attribute 'YOLOv10DetectionModel' on module 'ultralytics.nn.tasks'

### ISSUE THREAD

**Issue by thucnguyenduy** [THU-MIG/yolov10#59]
I encounter this error when running this training code, please help!

!yolo task=detect mode=train epochs=1 batch=16 plots=True \
model='/kaggle/input/123456/yolov10l.pt' \
data='/kaggle/input/filedata/data.yaml'

Traceback (most recent call last):
  File "/opt/conda/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/cfg/__init__.py", line 556, in entrypoint
    model = YOLO(model, task=task)
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/models/yolo/model.py", line 23, in __init__
    super().__init__(model=model, task=task, verbose=verbose)
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/engine/model.py", line 152, in __init__
    self._load(model, task=task)
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/engine/model.py", line 241, in _load
    self.model, self.ckpt = attempt_load_one_weight(weights)
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/nn/tasks.py", line 806, in attempt_load_one_weight
    ckpt, weight = torch_safe_load(weight)  # load ckpt
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/nn/tasks.py", line 732, in torch_safe_load
    ckpt = torch.load(file, map_location="cpu")
  File "/opt/conda/lib/python3.10/site-packages/torch/serialization.py", line 809, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/opt/conda/lib/python3.10/site-packages/torch/serialization.py", line 1172, in _load
    result = unpickler.load()
  File "/opt/conda/lib/python3.10/site-packages/torch/serialization.py", line 1165, in find_class
    return super().find_class(mod_name, name)
AttributeError: Can't get attribute 'YOLOv10DetectionModel' on <module 'ultralytics.nn.tasks' from '/opt/conda/lib/python3.10/site-packages/ultralytics/nn/tasks.py'>

**Comment by PrinceP** [comment]
pip install -e . after cloning this repo.

**Comment by abubow** [comment]
I want to use it using ultralytics through:
```python
from ultralytics import YOLO

# Load the YOLOv10 model
model = YOLO('yolov10n.pt') 
```
I want to use the model outside this repo. How would I do that?

**Comment by jameslahm** [comment]
Thanks for your interest! Could you please try to replace `YOLO('yolov10n.pt')` with `YOLOv10('yolov10n.pt')`?
> I want to use it using ultralytics through:
> 
> ```python
> from ultralytics import YOLO
> 
> # Load the YOLOv10 model
> model = YOLO('yolov10n.pt') 
> ```
> 
> I want to use the model outside this repo. How would I do that?

**Comment by fabrizioromanelli** [comment]
> I want to use it using ultralytics through:
> 
> ```python
> from ultralytics import YOLO
> 
> # Load the YOLOv10 model
> model = YOLO('yolov10n.pt') 
> ```
> 
> I want to use the model outside this repo. How would I do that?

It's impossible to use it in Ultralytics at this very moment. If you look at the Ultralytics documentation it says:
```
Coming Soon

The Ultralytics team is actively working on officially integrating the YOLOv10 models into the ultralytics package. Once the integration is complete, the usage examples shown below will be fully functional. Please stay tuned by following our social media and [GitHub repository](https://github.com/ultralytics/ultralytics) for the latest updates on YOLOv10 integration. We appreciate your patience and excitement! 🚀
```

**Comment by jrguignan** [comment]
Use this:

pip install -q git+https://github.com/THU-MIG/yolov10.git

**Comment by jameslahm** [comment]
Please feel free to reopen this issue if you have further questions.

**Comment by GTziolas** [comment]
@jrguignan 
Using the below code causes my ultralytics version to downgrade to 8.1.34, which in turn causes the error `AttributeError: module 'ray.tune' has no attribute 'is_session_enabled'` to appear again which was fixed in ultralytics version 8.1.38 [here](https://github.com/ultralytics/ultralytics/pull/9432)
> Use this:
> 
> pip install -q git+https://github.com/THU-MIG/yolov10.git

**Comment by rabion1234** [comment]
> Thanks for your interest! Could you please try to replace `YOLO('yolov10n.pt')` with `YOLOv10('yolov10n.pt')`?
NameError: name 'YOLOv10' is not defined 
 
This Error is showing

**Comment by DuckyBlender** [comment]
Cloned repo, ran `pip install -e .` and changed to YOLOv10 and works.
Please don't forget to change the import from `from ultralytics import YOLO` to `from ultralytics import YOLOv10`

**Comment by umarbutler** [comment]
> @jrguignan @jameslahm Using the below code:
> 
> > Use this:
> > pip install -q git+https://github.com/THU-MIG/yolov10.git
> 
> causes my ultralytics version to downgrade to 8.1.34, which in turn causes the error `AttributeError: module 'ray.tune' has no attribute 'is_session_enabled'` to appear again which was fixed in ultralytics version 8.1.38 [here](https://github.com/ultralytics/ultralytics/pull/9432)

Same problem. Cloning does not work since its the exact same code being installed anyways (I still tried it though).

**Comment by umarbutler** [comment]
Temporary hotfix is to go into `ultralytics/utils/callbacks/raytune.py` and update a single line of code as was done for v8.1.38 of Ultralytics: https://github.com/ultralytics/ultralytics/commit/1828cfe842eb45b9d4c098fda99d2515835b861b

@jameslahm ideally this should be implemented in your version. @ultralytics ideally YOLOv10 support should be merged upstream to Ultralytics so that bug and security fixes are applied.

**Comment by shunmian** [comment]
[ultralytics v8.2.38](https://github.com/ultralytics/ultralytics/releases/tag/v8.2.38) has updated to include YOLOv10.

**Comment by santhoshkumar3134** [comment]
(myenv) D:\santhoshkumar\human fall>python sample.py 
Traceback (most recent call last):
  File "D:\santhoshkumar\human fall\sample.py", line 2, in <module>
    from ultralytics import YOLO
  File "D:\santhoshkumar\human fall\myenv\Lib\site-packages\ultralytics\__init__.py", line 5, in <module>
    from ultralytics.data.explorer.explorer import Explorer
  File "D:\santhoshkumar\human fall\myenv\Lib\site-packages\ultralytics\data\explorer\explorer.py", line 18, in <module>
    from ultralytics.models.yolo.model import YOLO
  File "D:\santhoshkumar\human fall\myenv\Lib\site-packages\ultralytics\models\__init__.py", line 6, in <module>
    from .yolov10 import YOLOv10
  File "D:\santhoshkumar\human fall\myenv\Lib\site-packages\ultralytics\models\yolov10\__init__.py", line 1, in <module>
    from .model import YOLOv10
  File "D:\santhoshkumar\human fall\myenv\Lib\site-packages\ultralytics\models\yolov10\model.py", line 7, in <module>
    from huggingface_hub import PyTorchModelHubMixin
ModuleNotFoundError: No module named 'huggingface_hub'
