### ISSUE TITLE
How to predect a image with your codes?

### ISSUE THREAD

**Issue by chriszxk** [THU-MIG/yolov10#60]
Could you please tell us the codes about predect a image?
 use "yolo predect model=yolov10n.pt source="image path"?
 
thank you for your attention and time?

**Comment by jameslahm** [comment]
Thanks for your interest! Yes, it's correct.

> Could you please tell us the codes about predect a image? use "yolo predect model=yolov10n.pt source="image path"?
> 
> thank you for your attention and time?

**Comment by gboeer** [comment]
Not quite correct, it should be :
yolo ~predect~ **predict** model=yolov10n.pt source="image path"

**Comment by jameslahm** [comment]
Please feel free to reopen this issue if you have further questions.
