### ISSUE TITLE
AttributeError: 'str' object has no attribute 'view'

### ISSUE THREAD

**Issue by xinzhilii** [THU-MIG/yolov10#62]
File "/opt/data/private/yolov10-main/ultralytics/utils/loss.py", line 200, in <listcomp>
    pred_distri, pred_scores = torch.cat([xi.view(feats[0].shape[0], self.no, -1) for xi in feats], 2).split(
AttributeError: 'str' object has no attribute 'view'

**Comment by jameslahm** [comment]
Thanks for your interest! Does the issue #10 help?

**Comment by xinzhilii** [comment]
How can this place be corrected? File "/mnt/lixz/000_shiyi/yolov10-main/ultralytics/utils/loss.py", line 200, in __call__
    pred_distri, pred_scores = torch.cat([xi.view(feats[0].shape[0], self.no, -1) for xi in feats], 2).split(
  File "/mnt/lixz/000_shiyi/yolov10-main/ultralytics/utils/loss.py", line 200, in <listcomp>
    pred_distri, pred_scores = torch.cat([xi.view(feats[0].shape[0], self.no, -1) for xi in feats], 2).split(

**Comment by jameslahm** [comment]
Could you please provide the error information?

**Comment by xinzhilii** [comment]
AttributeError: 'str' object has no attribute 'view'

**Comment by xinzhilii** [comment]
The problem has already been settled.

**Comment by sang123111** [comment]
AttributeError: 'str' object has no attribute 'view'，How can I solve this problem

**Comment by EngHanaa** [comment]
I need to continue from last.pt file, but u have the same error "AttributeError: 'str' object has no attribute 'view'", also i have used YOLOv10 instead of YOLOv. How can i solve that?

**Comment by yslion** [comment]
I met the same issue ,  step1  : yolov10> yolo detect train data=custom_data.yaml model=yolov10m.pt epochs=10  imgsz=640 device=0 batch=-1   , got model  in runs\detect\train24\weights\best.pt   ,  step2   : yolo detect train data=new_data.yaml model=y runs\detect\train24\weights\best.pt   ,  got  "AttributeError: 'str' object has no attribute 'view'"  .  to solve it , do not use cli ,  use a py script instead : ```
from ultralytics import YOLOv10

model = YOLOv10(r'runs\detect\train24\weights\best.pt')
if __name__ == '__main__':
    model.train(data='new_data.yaml', epochs=50, batch=8, imgsz=640,device=0)
```
