### ISSUE TITLE
Can't get annotated labels when using YOLO v10 for the predictions via cli

### ISSUE THREAD

**Issue by justinjohn0306** [THU-MIG/yolov10#63]
I tried running this cmd: yolo predict model=yolov10x.pt show=True show_labels=True

**Comment by jameslahm** [comment]
Thanks for your interest! We have updated the checkpoints with other attributes, like class names. Could you please update the checkpoint and try again?

**Comment by justinjohn0306** [comment]
@jameslahm that did the trick it seems :)
