### ISSUE TITLE
The requirements of your YOLO version 10

### ISSUE THREAD

**Issue by nakanojinharuka** [THU-MIG/yolov10#65]
When I watched your 'requirements.txt' file, it says that the settings should be equal to specific version.

So, there is a question. I have used YOLO version 5, 8 and 9 and it seems like the python and packages (program runtime) of version 10 is similar to that on version 8. Could I use the creation process in establishing the version 8 environment to set up the runtime of version 10.

Thank you!

Reason: the requirements' text-file writes:

torch==2.0.1
torchvision==0.15.2
onnx==1.14.0
onnxruntime==1.15.1
pycocotools==2.0.7
PyYAML==6.0.1
scipy==1.13.0
onnxsim==0.4.36
onnxruntime-gpu==1.18.0

I have cuda with 12.1, torch 2.3.0 and torchvision 0.18.0. That's the reason why I make this issue.

**Comment by Starmilanoo** [comment]
https://d3js.org/d3.v6.min.js
