### ISSUE TITLE
Can I train YOLOv10 on Rectangular Images?

### ISSUE THREAD

**Issue by HassanBinHaroon** [THU-MIG/yolov10#68]
Can I train YOLOv10 on Rectangular Images? Like Image Size = (W=640, H=480)

I get the warning that the training is only possible with integer Image Size that means only squared images would be trained. 

@everyone @jameslahm @SkalskiP @tfriedel @PrashantDixit0 Please elaborate, Thanks!

**Comment by jameslahm** [comment]
Thanks for your interest! Could you please share the details of how to reproduce this issue?

**Comment by superbayes** [comment]
If the input image size is 640*480, does the model support it?

**Comment by jameslahm** [comment]
Yes, it is supported. Does this issue https://github.com/ultralytics/ultralytics/issues/235 help?

**Comment by PrashantDixit0** [comment]
@HassanBinHaroon Can you please share your code or sample dataset where you are getting this problem, so that it can be replicated ?

**Comment by HassanBinHaroon** [comment]
@PrashantDixit0 @jameslahm Actually, there is not any issue or problem, the code is being executed. Its just the confirmation as understanding the complete code is time consuming. So, asking right from the author that "**Can YOLOv10 be trained on Rectangular Images Successfully?**".

Actually there's not much log details that make sure the user what's the training input size.

**Comment by PrashantDixit0** [comment]
Yes ofcourse, you can give images of any size for training and inferencing it works :+1:

**Comment by HassanBinHaroon** [comment]
@PrashantDixit0 @jameslahm Is there any sanity check or information that shows the exact training image size of the model after starting the training? Sometimes code optimally computes the training image size to fulfill the architecture constraints. That computed image size maybe from what was intended and input. Please elaborate, thanks! 

> Yes ofcourse, you can give images of any size for training and inferencing it works 👍

Is that by turning on this Flag --rect=True, with input --imgsz=[h,w]?

**Comment by jameslahm** [comment]
Yes, it should work.
> @PrashantDixit0 @jameslahm Is there any sanity check or information that shows the exact training image size of the model after starting the training? Sometimes code optimally computes the training image size to fulfill the architecture constraints. That computed image size maybe different from what was intended and input. Please elaborate, thanks!
> 
> > Yes ofcourse, you can give images of any size for training and inferencing it works 👍
> 
> Is that by turning on this Flag --rect=True, with input --imgsz=[h,w]?

**Comment by jameslahm** [comment]
Please feel free to reopen this issue if you have further questions.
