### ISSUE TITLE
YOLOv10 isn't importing in Kaggle

### ISSUE THREAD

**Issue by aiknayan** [THU-MIG/yolov10#69]
Did run the same setup in Google Colab. But in Kaggle it ended up with error

![Screenshot_1](https://github.com/THU-MIG/yolov10/assets/28272092/82bdd745-97cd-48d8-89e5-e4d5f98031cf)

**Comment by aiknayan** [comment]
`!pip install -q git+https://github.com/THU-MIG/yolov10.git`

`!yolo task=detect mode=train model=yolov10n.yaml data="/kaggle/working/xml-and-coco-json-dataset/FAIR1M2.O_Data.yaml" epochs=50 pretrained=False lr0=0.005 momentum=0.9 optimizer='SGD' iou= 0.5 save_period= 1`


![Screenshot_2](https://github.com/THU-MIG/yolov10/assets/28272092/fdd6f1f5-c50e-4e3f-8c06-a4007eb585f3)

**Comment by jameslahm** [comment]
Thanks for your interest! Could you please check if the codebase is installed correctly?

**Comment by SkalskiP** [comment]
I just tried and looks like everything works: https://www.kaggle.com/code/skalskip/how-to-train-yolov10-on-a-custom-dataset

**Comment by aiknayan** [comment]
> I just tried and looks like everything works: https://www.kaggle.com/code/skalskip/how-to-train-yolov10-on-a-custom-dataset

Can you share the notebook permission to public? It isn't visible.

**Comment by aiknayan** [comment]
> I just tried and looks like everything works: https://www.kaggle.com/code/skalskip/how-to-train-yolov10-on-a-custom-dataset

Can you public your notebook? It's in private not visible.

**Comment by aiknayan** [comment]
Fixed All the issues. Thank You
