### ISSUE TITLE
如何理解模型输出output0：1 300 6

### ISSUE THREAD

**Issue by xinsuinizhuan** [THU-MIG/yolov10#7]
我导出了onnx模型，但是模型输出结构跟其他版本yolo不同，模型输出是 1 300 6，怎么理解呢？
![ff52df17af83308b5a5b52e7c6e3d98](https://github.com/THU-MIG/yolov10/assets/40679769/260e2c6e-123a-41fd-8219-7b83f635cd25)

**Comment by jameslahm** [comment]
Thanks for your interest! The output[:, :, :4] is the box location (xyxy), and output[:, :, 4] is the classification score, and output[:, :, 5] is the predicted class label.

**Comment by xinsuinizhuan** [comment]
但是，这个300呢？一次最多预测300个目标？

**Comment by xinsuinizhuan** [comment]
yolov8 直接是 8400，这里只有300

**Comment by jameslahm** [comment]
Yes, it's correct. The maximum number of targets to be detected can be controlled by `max_det` in the default.yaml.
> 但是，这个300呢？一次最多预测300个目标？

**Comment by xinsuinizhuan** [comment]
不对吧，我按照 x y w h classification_score index解析，一个目标都解析不出来：

是 x y x y，还是x y w h?

**Comment by jameslahm** [comment]
您好，是xyxy~

**Comment by helm-apprentice** [comment]
我在转为ONNX之后推倒没有问题，但是转为MNN之后，怎么每个检测框的得分都很高呢？不是1就是0.99

**Comment by thestars-maker** [comment]
能不能将其改为yolov8的输出呢

**Comment by AurevoirXavier** [comment]
> 您好，是xyxy~

Such an important things should be noted in the doc.

As, I don't use Python YOLO package. I always port these models to Rust and use ORT. This take me a half day to debug. At the begining I thought there might be something wrong with my training model.
