### ISSUE TITLE
5.27 更新 checkpoints with other attributes 存在问题：加载模型报错

### ISSUE THREAD

**Issue by xfkcode** [THU-MIG/yolov10#71]
![c16698db593fa121e7a6f4167876cba](https://github.com/THU-MIG/yolov10/assets/111849471/05e2b290-b57b-40ef-a454-adbb30345de8)

**Comment by jameslahm** [comment]
Thanks for your interest! Do you install the codebase by `pip install -e .`?

**Comment by xfkcode** [comment]
The issue has been resolved. It was an oversight on my part. Thank you for your assistance!
