### ISSUE TITLE
ONNX TopK

### ISSUE THREAD

**Issue by knoppmyth** [THU-MIG/yolov10#72]
Hi,

I built a model for a custom detector and exported it to ONNX for use with OpenCV. However when trying to run the model it errors with:
cv2.error: OpenCV(4.9.0) /io/opencv/modules/dnn/src/onnx/onnx_importer.cpp:1053: error: (-2:Unspecified error) in function 'handleNode'
 Node [TopK@ai.onnx]:(onnx_node!/model.23/TopK) parse error: OpenCV(4.9.0) /io/opencv/modules/dnn/src/net_impl.hpp:108: error: (-2:Unspecified error) Can't create layer "onnx_node!/model.23/TopK" of type "TopK" in function 'getLayerInstance'
 
Researching, it appears OpenCV doesn't currently support TopK. My confusion here is that I've exported various models from Ultralytics to ONNX and have no issues using those with OpenCV.

I've tried: 
yolo mode=export model=runs/detect/train/weights/best.pt format=onnx
yolo mode=export model=runs/detect/train/weights/best.pt format=onnx opset=11
yolo mode=export model=runs/detect/train/weights/best.pt format=onnx opset=11 simplify

All result in the same error. Can an ONNX export be done without the TopK operator?

Thanks.

**Comment by jameslahm** [comment]
Thanks for your interest! Could you please try to use tools like [onnx-modifier](https://github.com/ZhangGe6/onnx-modifier) to remove the onnx's postprocessing that contains TopK operations?

**Comment by knoppmyth** [comment]
You're welcome. Thank you for your work and support. I installed onnx-modifer and deleted 2 instances of TopK, I now get this error:

error: OpenCV(4.9.0) /io/opencv/modules/dnn/src/onnx/onnx_importer.cpp:1053: error: (-2:Unspecified error) in function 'handleNode' > Node [Mod@ai.onnx]:(onnx_node!/model.23/Mod) parse error: OpenCV(4.9.0) /io/opencv/modules/dnn/src/onnx/onnx_importer.cpp:596: error: (-5:Bad argument) Blob /model.23/TopK_1_output_1 not found in const blobs in function 'getBlob' >

I reloaded the original onnx file, and changed the input from the nodes before TopK to the output of the node before TopK then deleted the TopK nodes. I'm getting this error:

error: OpenCV(4.9.0) /io/opencv/modules/dnn/src/onnx/onnx_importer.cpp:1053: error: (-2:Unspecified error) in function 'handleNode' > Node [Mod@ai.onnx]:(onnx_node!/model.23/Mod) parse error: OpenCV(4.9.0) /io/opencv/modules/dnn/src/net_impl.hpp:108: error: (-2:Unspecified error) Can't create layer "onnx_node!/model.23/Mod" of type "Mod" in function 'getLayerInstance' >

**Comment by jameslahm** [comment]
Could you please try to delete all the nodes in the postprocessing rather than only  deleting the TopK nodes?

**Comment by knoppmyth** [comment]
I'm new to editing onnx files. Do you mean delete everything after Transpose?

![Screenshot_20240526_223900](https://github.com/THU-MIG/yolov10/assets/107227128/698fb4b0-e220-44a4-98f8-399f21d17e3d)

**Comment by jameslahm** [comment]
Yes, that is correct.
> I'm new to editing onnx files. Do you mean delete everything after Transpose?
> 
> ![Screenshot_20240526_223900](https://private-user-images.githubusercontent.com/107227128/333980047-698fb4b0-e220-44a4-98f8-399f21d17e3d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3ODkxMjUsIm5iZiI6MTcxNjc4ODgyNSwicGF0aCI6Ii8xMDcyMjcxMjgvMzMzOTgwMDQ3LTY5OGZiNGIwLWUyMjAtNDRhNC05OGY4LTM5OWYyMWQxN2UzZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyN1QwNTQ3MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMjQzNzNiMzY4NWU4Y2E0MzM4NjVkNDBhYmYzNmE0NDAzYjhlOTYwYmQ2N2I5NzNjYjY5YzAyMTI3NTM4NGRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iNBWYriIDFlrh5XazmWqhThQoCMI3TNQ_e3wP1bS11c)

**Comment by knoppmyth** [comment]
Thanks! That seems to be working. Will close after I do more testing.

**Comment by knoppmyth** [comment]
After further testing, I had to delete Transpose and all it's children. Thanks again for the pointer.

**Comment by victorsoyvictor** [comment]
> After further testing, I had to delete Transpose and all it's children. Thanks again for the pointer.

Could you share the cpp snippet? thanks.

**Comment by jasonlytehouse** [comment]
If you're curious about the code to do this, I have a script called [v10_fixer.py](https://github.com/jayfalls/jetson_nano_ubuntu20_docker/blob/main/yolo/v10_fixer.py) here that does this

**Comment by dengxiongshi** [comment]
> After further testing, I had to delete Transpose and all it's children. Thanks again for the pointer.

@knoppmyth Hello, I did the same as you. Do you know how to handle the post-processing？

**Comment by knoppmyth** [comment]
Hello @dengxiongshi What specifically do you mean by "post-processing"? With respect to using the model for inference, I don't believe I have any further issues. However I cannot remember for certain. I was able to test the model but it's performance for my dataset wasn't better than what I was previous using so, I never went further with YOLOV10.

**Comment by dengxiongshi** [comment]
@knoppmyth Hello, I got a question and didn't know what to do with the results of the detect model. Just like following:

<img width="1613" height="1644" alt="Image" src="https://github.com/user-attachments/assets/e10f9b8c-8f9d-4e0d-a897-3980519e5c36" />
I deleted the Transpose and all it's children. Then, I rewrote the post-processing operation and got an incorrect result.

**Comment by knoppmyth** [comment]
@dengxiongshi I cannot accurately remember if the results I got were wrong or not. I do remember that YOLOv10 wasn't better than YOLOv6 for my dataset so I didn't continue to experiment with v10. I'll look at my old code to see if I have any comments for v10. If I do, I'll post what I have else, I don't. 

By wrong, I personally mean some versions of YOLO returned the output in a differing formats and one would have to figure out the format and normalize it (whatever normal meant for them).

**Comment by knoppmyth** [comment]
@dengxiongshi Here is the function I used to normalize outputs from various YOLOs:
```
def post_detection_processing(confidence_level, detector, model_fam, network_width, network_height):
    global inference_output, image_width, image_height, boxes, scores, class_ids, class_list
    x_factor = image_width / network_width
    y_factor = image_height / network_height

    if model_fam == "ultralytics" or model_fam == "yolov6" or model_fam == "yolov10":
        for row in inference_output:
            if model_fam == "yolov6":
                classes_scores = row[5:]
            if model_fam == "ultralytics" or model_fam == "yolov10":
                classes_scores = row[4:]
            (_min_score, max_score, _min_class_loc, (_x, max_class_index)) = cv2.minMaxLoc(classes_scores)
            if max_score >= confidence_level:
                if model_fam == "yolov6" or model_fam == "ultralytics":
                    x, y, w, h = row[0].item(), row[1].item(), row[2].item(), row[3].item()
                    left = int((x - 0.5 * w) * x_factor)
                    top = int((y - 0.5 * h) * y_factor)
                    width = int(w * x_factor)
                    height = int(h * y_factor)
                if model_fam == "yolov10":
                    x1, y1, x2, y2 = row[0].item(), row[1].item(), row[2].item(), row[3].item()
                    w = x2 - x1
                    h = y2 - y1
                    left = int(x1 * x_factor)
                    top = int(y1 * y_factor)
                    width = int(w * x_factor)
                    height = int(h * y_factor)
                box = np.array([left, top, width, height])
                boxes.append(box)
                scores.append(max_score)
                class_ids.append(max_class_index)
    return boxes, class_ids, scores
```

**Comment by dengxiongshi** [comment]
> [@dengxiongshi](https://github.com/dengxiongshi) Here is the function I used to normalize outputs from various YOLOs:
> 
> ```
> def post_detection_processing(confidence_level, detector, model_fam, network_width, network_height):
>     global inference_output, image_width, image_height, boxes, scores, class_ids, class_list
>     x_factor = image_width / network_width
>     y_factor = image_height / network_height
> 
>     if model_fam == "ultralytics" or model_fam == "yolov6" or model_fam == "yolov10":
>         for row in inference_output:
>             if model_fam == "yolov6":
>                 classes_scores = row[5:]
>             if model_fam == "ultralytics" or model_fam == "yolov10":
>                 classes_scores = row[4:]
>             (_min_score, max_score, _min_class_loc, (_x, max_class_index)) = cv2.minMaxLoc(classes_scores)
>             if max_score >= confidence_level:
>                 if model_fam == "yolov6" or model_fam == "ultralytics":
>                     x, y, w, h = row[0].item(), row[1].item(), row[2].item(), row[3].item()
>                     left = int((x - 0.5 * w) * x_factor)
>                     top = int((y - 0.5 * h) * y_factor)
>                     width = int(w * x_factor)
>                     height = int(h * y_factor)
>                 if model_fam == "yolov10":
>                     x1, y1, x2, y2 = row[0].item(), row[1].item(), row[2].item(), row[3].item()
>                     w = x2 - x1
>                     h = y2 - y1
>                     left = int(x1 * x_factor)
>                     top = int(y1 * y_factor)
>                     width = int(w * x_factor)
>                     height = int(h * y_factor)
>                 box = np.array([left, top, width, height])
>                 boxes.append(box)
>                 scores.append(max_score)
>                 class_ids.append(max_class_index)
>     return boxes, class_ids, scores
> ```

Thank you very much!

**Comment by knoppmyth** [comment]
@dengxiongshi You're very welcome.
