### ISSUE TITLE
About batchsize

### ISSUE THREAD

**Issue by Godk02** [THU-MIG/yolov10#73]
Thanks for your work!
I set the batchsize to 16, and train did not report any errors during the training process. However, I noticed that the batch size of val was 8. And I used 4 gpus.

The number of training images is 4000,and the number of val images is 1000, when I train, the log is
![image](https://github.com/THU-MIG/yolov10/assets/145435036/72dd3a78-1373-4c65-9868-b9f293541794)
![image](https://github.com/THU-MIG/yolov10/assets/145435036/fca31488-ad90-4e36-a1f9-3dca2e8f275a)

If the batch is 16, the 125 should be 63,right?

My question is: where can I set the batchsize of val during the training process？

**Comment by jameslahm** [comment]
Thanks for your interest! The validation is only performed on the first device.
https://github.com/THU-MIG/yolov10/blob/25ef427c47045e99cddd4c5388f3c89bc30264c2/ultralytics/engine/trainer.py#L423-L434

And the batch size of validation is 2* batch size of training.
https://github.com/THU-MIG/yolov10/blob/25ef427c47045e99cddd4c5388f3c89bc30264c2/ultralytics/engine/trainer.py#L294-L296

So the iter number is 1000 / (16/4 * 2) = 125.

**Comment by Godk02** [comment]
> Thanks for your interest! The validation is only performed on the first device.
> 
> https://github.com/THU-MIG/yolov10/blob/25ef427c47045e99cddd4c5388f3c89bc30264c2/ultralytics/engine/trainer.py#L423-L434
> 
> And the batch size of validation is 2* batch size of training, by default.
> 
> https://github.com/THU-MIG/yolov10/blob/25ef427c47045e99cddd4c5388f3c89bc30264c2/ultralytics/engine/trainer.py#L294-L296
> 
> So the iter number is 1000 / (16/4 * 2) = 125.

Thank you for your response! I have noticed that there are same settings in YOLOv8.
