### ISSUE TITLE
Matched extra labels

### ISSUE THREAD

**Issue by xy3xy3** [THU-MIG/yolov10#77]
```python
from ultralytics import YOLOv10
from ultralytics.nn.autobackend import default_class_names
model = YOLOv10("models/yolov10n.pt").to("cuda")
model.model.names=default_class_names("coco8.yaml")
res = model.predict("bus.jpg",
                    classes=[0],
                  show_boxes=True,show_conf=True,show_labels=True)[0]
res.show()
```
The input for classes is only 0, which means only to match people, but it also matches bus.
![image](https://github.com/THU-MIG/yolov10/assets/25221048/bf9f32ff-a60d-4e31-ba58-b1faa5577a5e)

It's fine on YOLO v8.
```python
from ultralytics import YOLOv10 , YOLO
from ultralytics.nn.autobackend import default_class_names
# model = YOLOv10("models/yolov10n.pt").to("cuda")
# model.model.names=default_class_names("coco8.yaml")
model = YOLO("yolov8s.pt").to("cuda")
res = model.predict("bus.jpg",
                    classes=[0],
                  show_boxes=True,show_conf=True,show_labels=True)[0]
res.show()
```
![image](https://github.com/THU-MIG/yolov10/assets/25221048/1db3789a-a92e-437c-bda5-7af77a2854cb)

**Comment by jameslahm** [comment]
Thanks! We just fixed this issue. Could you please update the codebase and try again? Besides, you could also try our updated [checkpoints](https://github.com/THU-MIG/yolov10/releases/tag/v1.1) with other attributes, like class names. So this line `model.model.names=default_class_names("coco8.yaml")` can be removed for prediction.

**Comment by xy3xy3** [comment]
> class_names

It seems doesn't work.I 've updated the model and ultralytics.
![image](https://github.com/THU-MIG/yolov10/assets/25221048/8d5afe0c-92e3-4530-8174-940a73c25223)

```python
from ultralytics import YOLOv10
model = YOLOv10("models/yolov10n.pt").to("cuda")
res = model.predict("bus.jpg",
                    # classes=["person"],
                    classes=[0],
                  show_boxes=True,show_conf=True,show_labels=True)[0]
res.show()
```

**Comment by jameslahm** [comment]
Could you please check that your codebase is the latest version? For the same code, my output has no bus
![image](https://github.com/THU-MIG/yolov10/assets/43805318/b9f471e6-2ed0-4cf8-9b1b-b2cf237f7cc2)
