### ISSUE TITLE
Hello, during the first round of training, the error is as follows: Is there a solution to it?

### ISSUE THREAD

**Issue by wyyt1202** [THU-MIG/yolov10#8]
Traceback (most recent call last):
File "/home/amax/.conda/envs/zw_yolo/bin/yolo", line 8, in
sys.exit(entrypoint())
File "/data1/moxing/wsy/ZW/wyy/yolov10-main/ultralytics/cfg/init.py", line 586, in entrypoint
getattr(model, mode)(**overrides) # default args from model
File "/data1/moxing/wsy/ZW/wyy/yolov10-main/ultralytics/engine/model.py", line 657, in train
self.trainer.train()
File "/data1/moxing/wsy/ZW/wyy/yolov10-main/ultralytics/engine/trainer.py", line 213, in train
self._do_train(world_size)
File "/data1/moxing/wsy/ZW/wyy/yolov10-main/ultralytics/engine/trainer.py", line 430, in _do_train
self.metrics, self.fitness = self.validate()
File "/data1/moxing/wsy/ZW/wyy/yolov10-main/ultralytics/engine/trainer.py", line 552, in validate
metrics = self.validator(self)
File "/home/amax/.conda/envs/zw_yolo/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
return func(*args, **kwargs)
File "/data1/moxing/wsy/ZW/wyy/yolov10-main/ultralytics/engine/validator.py", line 187, in call
preds = self.postprocess(preds)
File "/data1/moxing/wsy/ZW/wyy/yolov10-main/ultralytics/models/yolov10/val.py", line 18, in postprocess
boxes, scores, labels = ops.v10postprocess(preds, self.args.max_det)
File "/data1/moxing/wsy/ZW/wyy/yolov10-main/ultralytics/utils/ops.py", line 852, in v10postprocess
assert(4 + nc == preds.shape[-1])
AssertionError

**Comment by DLxiaoming** [comment]
the same problem...

**Comment by Youareabigpig** [comment]
+1，how to solve？

**Comment by Z-alchemist** [comment]
同问

**Comment by jameslahm** [comment]
Thanks for your interest! We just fixed this issue. Could you please update the codebase and try again? Thanks!

**Comment by DLxiaoming** [comment]
The issue with downloading the code again is still unresolved...
![Uploading image.png…]()

**Comment by jameslahm** [comment]
I cannot see the image you uploaded. Could you please upload the image again? Thanks!

**Comment by DLxiaoming** [comment]
![Uploading 1716537548403.jpg…]()

**Comment by bkpagen** [comment]
+1

**Comment by jameslahm** [comment]
Hi, your code seems not to be the latest version. For example, Line 18 in val.py is now like below https://github.com/THU-MIG/yolov10/blob/66bca50c4745411eeb6846b4ae7437c462a11a5d/ultralytics/models/yolov10/val.py#L18
> > 我看不到您上传的图片。您能再上传一下吗？谢谢！
> 
> Traceback (most recent call last): File "D:\Anaconda3\envs\yolov10\lib\runpy.py", line 197, in _run_module_as_main return _run_code(code, main_globals, None, File "D:\Anaconda3\envs\yolov10\lib\runpy.py", line 87, in _run_code exec(code, run_globals) File "D:\Anaconda3\envs\yolov10\Scripts\yolo.exe__main__.py", line 7, in File "C:\Users\Administrator\Downloads\yolov10-main\yolov10-main\ultralytics\cfg__init__.py", line 586, in entrypoint getattr(model, mode)(**overrides) # default args from model File "C:\Users\Administrator\Downloads\yolov10-main\yolov10-main\ultralytics\engine\model.py", line 657, in train self.trainer.train() File "C:\Users\Administrator\Downloads\yolov10-main\yolov10-main\ultralytics\engine\trainer.py", line 213, in train self._do_train(world_size) File "C:\Users\Administrator\Downloads\yolov10-main\yolov10-main\ultralytics\engine\trainer.py", line 430, in _do_train self.metrics, self.fitness = self.validate() File "C:\Users\Administrator\Downloads\yolov10-main\yolov10-main\ultralytics\engine\trainer.py", line 552, in validate metrics = self.validator(self) File "D:\Anaconda3\envs\yolov10\lib\site-packages\torch\utils_contextlib.py", line 115, in decorate_context return func(*args, **kwargs) File "C:\Users\Administrator\Downloads\yolov10-main\yolov10-main\ultralytics\engine\validator.py", line 187, in **call** preds = self.postprocess(preds) File "C:\Users\Administrator\Downloads\yolov10-main\yolov10-main\ultralytics\models\yolov10\val.py", line 18, in postprocess boxes, scores, labels = ops.v10postprocess(preds, self.args.max_det) File "C:\Users\Administrator\Downloads\yolov10-main\yolov10-main\ultralytics\utils\ops.py", line 853, in v10postprocess assert(4 + nc == preds.shape[-1]) AssertionError

**Comment by DLxiaoming** [comment]
> Hi, your code seems not to be the latest version. For example, Line 18 in val.py is now like below
> 
> https://github.com/THU-MIG/yolov10/blob/66bca50c4745411eeb6846b4ae7437c462a11a5d/ultralytics/models/yolov10/val.py#L18
> 
> > > 我看不到您上传的图片。您能再上传一下吗？谢谢！
> > 
> > 
> > Traceback (most recent call last): File "D:\Anaconda3\envs\yolov10\lib\runpy.py", line 197, in _run_module_as_main return _run_code(code, main_globals, None, File "D:\Anaconda3\envs\yolov10\lib\runpy.py", line 87, in _run_code exec(code, run_globals) File "D:\Anaconda3\envs\yolov10\Scripts\yolo.exe__main__.py", line 7, in File "C:\Users\Administrator\Downloads\yolov10-main\yolov10-main\ultralytics\cfg__init__.py", line 586, in entrypoint getattr(model, mode)(**overrides) # default args from model File "C:\Users\Administrator\Downloads\yolov10-main\yolov10-main\ultralytics\engine\model.py", line 657, in train self.trainer.train() File "C:\Users\Administrator\Downloads\yolov10-main\yolov10-main\ultralytics\engine\trainer.py", line 213, in train self._do_train(world_size) File "C:\Users\Administrator\Downloads\yolov10-main\yolov10-main\ultralytics\engine\trainer.py", line 430, in _do_train self.metrics, self.fitness = self.validate() File "C:\Users\Administrator\Downloads\yolov10-main\yolov10-main\ultralytics\engine\trainer.py", line 552, in validate metrics = self.validator(self) File "D:\Anaconda3\envs\yolov10\lib\site-packages\torch\utils_contextlib.py", line 115, in decorate_context return func(*args, **kwargs) File "C:\Users\Administrator\Downloads\yolov10-main\yolov10-main\ultralytics\engine\validator.py", line 187, in **call** preds = self.postprocess(preds) File "C:\Users\Administrator\Downloads\yolov10-main\yolov10-main\ultralytics\models\yolov10\val.py", line 18, in postprocess boxes, scores, labels = ops.v10postprocess(preds, self.args.max_det) File "C:\Users\Administrator\Downloads\yolov10-main\yolov10-main\ultralytics\utils\ops.py", line 853, in v10postprocess assert(4 + nc == preds.shape[-1]) AssertionError


Hello, thank you for your reply. A new error occurred after downloading the new code.
Starting training for 5 epochs...

      Epoch    GPU_mem     box_om     cls_om     dfl_om     box_oo     cls_oo     dfl_oo  Instances       Size
        1/5      5.61G      3.963      5.568      3.315      3.807      19.03      3.177         45        640: 100%|██████████| 146/146 [00:34<00:00,  4.18it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:01<00:00,  5.87it/s]
Traceback (most recent call last):
  File "D:\Anaconda3\envs\yolov10\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Anaconda3\envs\yolov10\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Anaconda3\envs\yolov10\Scripts\yolo.exe\__main__.py", line 7, in <module>
  File "C:\Users\Administrator\Downloads\yolov10-main\yolov10-main\ultralytics\cfg\__init__.py", line 586, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "C:\Users\Administrator\Downloads\yolov10-main\yolov10-main\ultralytics\engine\model.py", line 657, in train
    self.trainer.train()
  File "C:\Users\Administrator\Downloads\yolov10-main\yolov10-main\ultralytics\engine\trainer.py", line 213, in train
    self._do_train(world_size)
  File "C:\Users\Administrator\Downloads\yolov10-main\yolov10-main\ultralytics\engine\trainer.py", line 430, in _do_train
    self.metrics, self.fitness = self.validate()
  File "C:\Users\Administrator\Downloads\yolov10-main\yolov10-main\ultralytics\engine\trainer.py", line 552, in validate
    metrics = self.validator(self)
  File "D:\Anaconda3\envs\yolov10\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Administrator\Downloads\yolov10-main\yolov10-main\ultralytics\engine\validator.py", line 203, in __call__
    assert(self.args.save_json and self.jdict)
AssertionError

**Comment by jameslahm** [comment]
Thanks! It seems that your code is still not the latest version. For example, Line 203 in validator.py is now like below
https://github.com/THU-MIG/yolov10/blob/66bca50c4745411eeb6846b4ae7437c462a11a5d/ultralytics/engine/validator.py#L202-L211
Could you please update the codebase again? Thanks!

**Comment by DLxiaoming** [comment]
> 谢谢！看来你的代码仍然不是最新版本。例如，validator.py 中的第 203 行现在如下所示
> 
> https://github.com/THU-MIG/yolov10/blob/66bca50c4745411eeb6846b4ae7437c462a11a5d/ultralytics/engine/validator.py#L202-L211
> 
> 
> 您能再次更新代码库吗？谢谢！

Thank you for your answer. The problem has been resolved!

**Comment by jameslahm** [comment]
Thank you! Glad to hear it.
