### ISSUE TITLE
inference speed on Jetson AGX Xavier

### ISSUE THREAD

**Issue by arminiusresistance** [THU-MIG/yolov10#81]
I am trying the algorithm on Jetson AGX Xavier, but I'm having some setback to get it running.

Have you tried this algorithm on Jetson AGX and the model fit it? In case yes, what speed was achieved on 1080HD?

**Comment by jameslahm** [comment]
Thanks for your interest! We are sorry that we don't have the Jetson AGX device and cannot test the model on it. Could you please provide the details about the setback?

**Comment by bxtbold** [comment]
Hey @arminiusresistance, were you able to successfully run `yolov10` on your Jetson?

**Comment by jameslahm** [comment]
@arminiusresistance @bxtbold Does #157 help?

**Comment by jameslahm** [comment]
Please feel free to reopen this issue if you have further questions.
