### ISSUE TITLE
操作不直观

### ISSUE THREAD

**Issue by sporterman** [THU-MIG/yolov10#83]
希望能直接用python命令行操作，目前这种方式不利于代码二次开发

**Comment by sporterman** [comment]
是的，现在的使用方式，如果想调整网络结构会不太方便，之前的yolos系列的使用方式会更加方便二次开发，现在这个感觉封装度有点高，不好找源码调整

**Comment by jameslahm** [comment]
您好，如果想调整网络结构，比如修改已有模块，可以在`ultralytics/nn/modules/block.py`文件中进行修改，如果想添加新的结构，可以在`ultralytics/cfg/models/v10/yolov10s.yaml`中修改为新的结构名，并在`ultralytics/nn/modules/block.py`里添加新的结构~

**Comment by sporterman** [comment]
好的，目前这个项目的单张或者批次推理代码在哪个路径？能否支持将模型转格式到torchscript，因为里面还涉及到重参数化，不确定训练出来的模型是否可以直接转，还是需要export一次，然后再转到torchscript模型

**Comment by jameslahm** [comment]
您好，
您可以执行以下命令进行预测
```
yolo predict model=yolov8n/s/m/b/l/x.pt source=image.png
```
您可以直接执行以下命令导出到torchscript
```
yolo export model=yolov8n/s/m/b/l/x.pt imgsz=640
```

**Comment by sporterman** [comment]
上面的predict和export具体用到哪个脚本呢？对应的输入参数有哪些，比如yolo export中的format， 能支持多少种格式？

**Comment by jameslahm** [comment]
您好，`ultralytics/cfg/__init__.py`是脚本入口
> 上面的predict和export具体用到哪个脚本呢？

您好，我们测试过onnx和tensorrt，您可以参考README里进行测试，其他支持的格式，您可以参考这里https://docs.ultralytics.com/modes/export/#export-formats
> 比如yolo export中的format， 能支持多少种格式？

**Comment by sporterman** [comment]
好的，感谢您的耐心解答，非常棒的项目，点赞~
