### ISSUE TITLE
onnxruntime-gpu install error

### ISSUE THREAD

**Issue by Arnav-Aggarwal13** [THU-MIG/yolov10#86]
Hi,

I have a mac with the M1 chip. When trying to download the packages for yolov10 I got this error.

ERROR: Could not find a version that satisfies the requirement onnxruntime-gpu==1.18.0 (from versions: none)
ERROR: No matching distribution found for onnxruntime-gpu==1.18.0

It seems like the m1 chip doesn't support onnxruntime-gpu. Is there a workaround to this for Macs with the m1 chip?

**Comment by jameslahm** [comment]
Thanks for your interest! Could you please try to remove `onnxruntime-gpu==1.18.0` in the requirements.txt? This dependency is not necessary.

**Comment by jameslahm** [comment]
Please feel free to reopen this issue if you have further questions.
