### ISSUE TITLE
The size of tensor a (8400) must match the size of tensor b (16800) at non-singleton dimension 1

### ISSUE THREAD

**Issue by Mrtigerhandsome** [THU-MIG/yolov10#9]
File "D:\yolov10-main\yolov10-main\ultralytics\utils\tal.py", line 314, in dist2bbox
    x1y1 = anchor_points - lt
           ~~~~~~~~~~~~~~^~~~
RuntimeError: The size of tensor a (8400) must match the size of tensor b (16800) at non-singleton dimension 1

In function def dist2bbox

I try to print shape of anchor_points,lt and rb,they are in different shapr.
print(anchor_points.shape)
 print(lt.shape)
 print(rb.shape)
torch.Size([8400, 2])
torch.Size([1, 16800, 2])
torch.Size([1, 16800, 2])
How can i sove this issure

**Comment by Mrtigerhandsome** [comment]
I tried to train yolov10, but the following error occurred
Traceback (most recent call last):
  File "D:\yolov10-main\yolov10-main\train.py", line 5, in <module>
    results = model.train(data=r'D:\yolov10-main\yolov10-main\ultralytics\cfg\datasets\coco128.yaml',workers=0,epochs=100,batch=1)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\yolov10-main\yolov10-main\ultralytics\engine\model.py", line 657, in train
    self.trainer.train()
  File "D:\yolov10-main\yolov10-main\ultralytics\engine\trainer.py", line 213, in train
    self._do_train(world_size)
  File "D:\yolov10-main\yolov10-main\ultralytics\engine\trainer.py", line 381, in _do_train
    self.loss, self.loss_items = self.model(batch)
                                 ^^^^^^^^^^^^^^^^^
  File "C:\Users\Tiger\anaconda3\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tiger\anaconda3\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\yolov10-main\yolov10-main\ultralytics\nn\tasks.py", line 93, in forward
    return self.loss(x, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\yolov10-main\yolov10-main\ultralytics\nn\tasks.py", line 275, in loss
    return self.criterion(preds, batch)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\yolov10-main\yolov10-main\ultralytics\utils\loss.py", line 228, in __call__
    pred_bboxes = self.bbox_decode(anchor_points, pred_distri)  # xyxy, (b, h*w, 4)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\yolov10-main\yolov10-main\ultralytics\utils\loss.py", line 194, in bbox_decode
    return dist2bbox(pred_dist, anchor_points, xywh=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\yolov10-main\yolov10-main\ultralytics\utils\tal.py", line 316, in dist2bbox
    x1y1 = anchor_points - lt
           ~~~~~~~~~~~~~~^~~~
RuntimeError: The size of tensor a (8400) must match the size of tensor b (16800) at non-singleton dimension 1

**Comment by jameslahm** [comment]
Thanks! I cannot reproduce this issue in my local environment. My command is
```
yolo detect train data=coco128.yaml model=yolov10n.yaml epochs=100 batch=1 device=0
```
And it's training normally like below

![image](https://github.com/THU-MIG/yolov10/assets/43805318/9ad0507c-004a-4bb4-b4b9-d7de517b25d8)

Could you please check that your code is the latest version? Thanks.

**Comment by jameslahm** [comment]
Please feel free to reopen this issue if you have further questions.

**Comment by SM2XWe1L** [comment]
> I tried to train yolov10, but the following error occurred Traceback (most recent call last): File "D:\yolov10-main\yolov10-main\train.py", line 5, in results = model.train(data=r'D:\yolov10-main\yolov10-main\ultralytics\cfg\datasets\coco128.yaml',workers=0,epochs=100,batch=1) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\yolov10-main\yolov10-main\ultralytics\engine\model.py", line 657, in train self.trainer.train() File "D:\yolov10-main\yolov10-main\ultralytics\engine\trainer.py", line 213, in train self._do_train(world_size) File "D:\yolov10-main\yolov10-main\ultralytics\engine\trainer.py", line 381, in _do_train self.loss, self.loss_items = self.model(batch) ^^^^^^^^^^^^^^^^^ File "C:\Users\Tiger\anaconda3\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl return self._call_impl(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\Tiger\anaconda3\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl return forward_call(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\yolov10-main\yolov10-main\ultralytics\nn\tasks.py", line 93, in forward return self.loss(x, _args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\yolov10-main\yolov10-main\ultralytics\nn\tasks.py", line 275, in loss return self.criterion(preds, batch) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\yolov10-main\yolov10-main\ultralytics\utils\loss.py", line 228, in **call** pred_bboxes = self.bbox_decode(anchor_points, pred_distri) # xyxy, (b, h_w, 4) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\yolov10-main\yolov10-main\ultralytics\utils\loss.py", line 194, in bbox_decode return dist2bbox(pred_dist, anchor_points, xywh=False) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\yolov10-main\yolov10-main\ultralytics\utils\tal.py", line 316, in dist2bbox x1y1 = anchor_points - lt ~~~~~~~~~~~~~~^~~~ RuntimeError: The size of tensor a (8400) must match the size of tensor b (16800) at non-singleton dimension 1

Hello！ I encountered totally the same problem as yours when i try to quantize yolov8 model ,and i really want to know if you have solved the problem.If so ,can you publish your method?

Thanks!
