### ISSUE TITLE
install failed

### ISSUE THREAD

**Issue by lovehuanhuan** [THU-MIG/yolov10#90]
ls
CONTRIBUTING.md  README.md    docker  examples  mkdocs.yml      requirements.txt  ultralytics
LICENSE          custom.yaml  docs    figures   pyproject.toml  tests
root@d23379bf052c:/mnt# pip install -e .
WARNING: Ignoring invalid distribution -nnx (/opt/conda/lib/python3.8/site-packages)
ERROR: File "setup.py" or "setup.cfg" not found. Directory cannot be installed in editable mode: /mnt
(A "pyproject.toml" file was found, but editable mode currently requires a setuptools-based build.)
WARNING: Ignoring invalid distribution -nnx (/opt/conda/lib/python3.8/site-packages)
WARNING: Ignoring invalid distribution -nnx (/opt/conda/lib/python3.8/site-packages)
WARNING: Ignoring invalid distribution -nnx (/opt/conda/lib/python3.8/site-packages)
root@d23379bf052c:/mnt#

**Comment by jameslahm** [comment]
Thanks for your interest! Could you please try to follow the installation process in README?
```
conda create -n yolov10 python=3.9
conda activate yolov10
pip install -r requirements.txt
pip install -e .
```

**Comment by ckmessi** [comment]
Hi, @lovehuanhuan, 
Option#1: You can install the package without the editable flag:
```
pip install .
```

Option#2: Upgrading pip>=22.0 may also resolve this issue:
```
pip install pip==22.1.2
```

Please refer to https://github.com/ultralytics/ultralytics/issues/9832#issuecomment-2041527487



Hi, @jameslahm, maybe the following line can be added to `requirement.txt`, in case anyone wants to use an existing conda environment where the version of `pip` is lower than `22.0`
```
pip>=22.0
```

**Comment by SkalskiP** [comment]
Hi, you should be able to just do:

```python
pip install git+https://github.com/THU-MIG/yolov10.git
```

**Comment by jameslahm** [comment]
Please feel free to reopen this issue if you have further questions.
