### ISSUE TITLE
能否输出coco指标

### ISSUE THREAD

**Issue by ZZQ565697818** [THU-MIG/yolov10#91]
作者你好，请问您有尝试过将输出的yolo指标转换成coco指标吗，我在设置save_json=True后想尝试使用网上的代码使用predicitons.json来得到coco指标，出现了如下问题：
Traceback (most recent call last):
  File "get_COCO_metrice.py", line 19, in <module>
    pred = anno.loadRes(pred_json)  # init predictions api
  File "/opt/conda/envs/yolo/lib/python3.8/site-packages/pycocotools/coco.py", line 327, in loadRes
    assert set(annsImgIds) == (set(annsImgIds) & set(self.getImgIds())), \
AssertionError: Results do not correspond to current coco set

**Comment by jameslahm** [comment]
感谢你的关注！您好，现在代码里应该是支持训练和测试输出coco指标的，
训练时：https://github.com/THU-MIG/yolov10/blob/62aaafb3a0bcc17224b797ae4e9af65d7f29773f/ultralytics/engine/validator.py#L208
测试时：https://github.com/THU-MIG/yolov10/blob/62aaafb3a0bcc17224b797ae4e9af65d7f29773f/ultralytics/engine/validator.py#L221

**Comment by jameslahm** [comment]
Please feel free to reopen this issue if you have further questions.

**Comment by Get1star** [comment]
> Please feel free to reopen this issue if you have further questions.

您好，请问这个该怎么执行才能输出COCO评估指标

**Comment by hqg19971124** [comment]
遇到同样的问题 请问有解决吗
