### ISSUE TITLE
AttributeError: 'str' object has no attribute 'view'

### ISSUE THREAD

**Issue by sang123111** [THU-MIG/yolov10#92]
File "E:\yolov10-main\ultralytics\utils\loss.py", line 200, in <listcomp>
    pred_distri, pred_scores = torch.cat([xi.view(feats[0].shape[0], self.no, -1) for xi in feats], 2).split(
AttributeError: 'str' object has no attribute 'view'

**Comment by jameslahm** [comment]
Thanks for your interest! Does the issue https://github.com/THU-MIG/yolov10/issues/10 help?

**Comment by sang123111** [comment]
> Thanks for your interest! Does the issue #10 help?
thank you
