### ISSUE TITLE
OpenVINO

### ISSUE THREAD

**Issue by rhelck** [THU-MIG/yolov10#95]
Hey guys,

Firstly nice work on model, it is working well for me.
Can you guys provide a reproducible example of exporting Yolov10 to OpenvVino format please? 
Thanks!

**Comment by rhelck** [comment]
Never mind looks like i found it!

https://github.com/openvinotoolkit/openvino_notebooks/blob/0ba3c0211bcd49aa860369feddffdf7273a73c64/notebooks/yolov10-optimization/yolov10-optimization.ipynb

**Comment by jameslahm** [comment]
Wow, that's cool!
