### ISSUE TITLE
Bounding BOX Label printing of picture

### ISSUE THREAD

**Issue by rabion1234** [THU-MIG/yolov10#96]
First of all. nice model. It is working fine for me. I am wondering if it can print Predicted Bounding box with class label.

**Comment by jameslahm** [comment]
Thanks for your interest! We have updated the checkpoint with class names. Could you update the codebase and [checkpoints](https://github.com/THU-MIG/yolov10/releases/tag/v1.1), and try again?

**Comment by rabion1234** [comment]
no in prediction i want to print bounding box not want picture with bounding box.

**Comment by jameslahm** [comment]
You could obtain the bounding box and class names in here. `pred[:, :4]` is the bounding box and `pred[:, 5:6]` is the class name.
https://github.com/THU-MIG/yolov10/blob/62aaafb3a0bcc17224b797ae4e9af65d7f29773f/ultralytics/models/yolov10/predict.py#L33-L38

**Comment by SkalskiP** [comment]
Hi @rabion1234, if you use `supervision`, you could do something like this. IT will draw all the boxes and labels for you.

```python
import cv2
import supervision as sv
from ultralytics import YOLOv10

model = YOLOv10('yolov10n.pt')
image = cv2.imread('dog.jpeg')
results = model(image)[0]
detections = sv.Detections.from_ultralytics(results)

bounding_box_annotator = sv.BoundingBoxAnnotator()
label_annotator = sv.LabelAnnotator()

annotated_image = bounding_box_annotator.annotate(
    scene=image, detections=detections)
annotated_image = label_annotator.annotate(
    scene=annotated_image, detections=detections)
```

![download - 2024-05-28T092550 271](https://github.com/THU-MIG/yolov10/assets/26109316/d305cd11-f1e5-4e35-9db7-bab5c846c5b8)

**Comment by rabion1234** [comment]
hello  @jameslahm 
this is the result of code:
code:  !yolo task=detect mode=predict conf=0.25 save=True model=/content/yolov10/runs/detect/train4/weights/best.pt source=/content/pos_4_bgr_jpg.rf.d598e44f01bb7092d6b02e0fa39f4291_cropped_57.jpg

result Ultralytics YOLOv8.1.34 🚀 Python-3.10.12 torch-2.3.0+cu121 CPU (Intel Xeon 2.20GHz)
YOLOv10x summary (fused): 503 layers, 31591784 parameters, 0 gradients, 169.8 GFLOPs

image 1/1 /content/pos_4_bgr_jpg.rf.d598e44f01bb7092d6b02e0fa39f4291_cropped_57.jpg: 640x448 1 Not ok Positive cell, 1 Positive cell, 2582.9ms
Speed: 4.0ms preprocess, 2582.9ms inference, 1.5ms postprocess per image at shape (1, 3, 640, 448)
Results saved to runs/detect/predict4
💡 Learn more at https://docs.ultralytics.com/modes/predict

but when i check my image predicted class is correct one. i guess both class are predicted but higher confidence one will be printed but can you check what is the issue?
also one more i want that my use case is only to print in text my label and i don't want to save image and post process image .but i don't want to it.

**Comment by rabion1234** [comment]
for reproduction link https://colab.research.google.com/drive/1i4aBc6KsU0cKOD0Ok6tTZ2fG9HOZFFv2?usp=sharing

**Comment by jameslahm** [comment]
We have requested access to your reproduction colab, could you please agree it? Thank you.

**Comment by rabion1234** [comment]
sorry for troble! Now access granted
